<?php
require_once __DIR__.'/lowe-dashboard-common.php';
function ct_h($v){return ld_h($v);}function ct_mk($d){return date('Y-m',strtotime((string)$d));}function ct_ml($m){return date('M y',strtotime($m.'-01'));}
function ct_field(array $r,array $names,$default=''){foreach($names as $n){if(array_key_exists($n,$r)&&$r[$n]!==''&&$r[$n]!==null)return $r[$n];}return $default;}
function ct_total_cost(array $r):float{return ld_purchase_total($r);}
function ct_cost_lb(array $r):float{return ld_purchase_cost_lb($r);}
try{$p=ld_rows('Purchases');}catch(Throwable $e){die(ld_h($e->getMessage()));}
$latest=null;foreach($p as $r){$d=of_date($r['Receipt Date']??'');if($d&&($latest===null||$d>$latest))$latest=$d;}if(!$latest)die('No purchase history found.');$latestMonth=ct_mk($latest);$months=[];for($i=0;$i<13;$i++)$months[]=date('Y-m',strtotime($latestMonth.'-01 -'.$i.' months'));
$groups=[];foreach($p as $r){$d=of_date($r['Receipt Date']??'');if(!$d)continue;$sup=trim((string)($r['Supplier Name']??''));$prod=trim((string)($r['Product Name']??''));if($sup===''||$prod==='')continue;$m=ct_mk($d);if(!in_array($m,$months,true))continue;$k=ld_key($sup).'|'.ld_key($prod);if(!isset($groups[$k]))$groups[$k]=['supplier'=>$sup,'product'=>$prod,'months'=>[],'latest_date'=>null,'latest_cost'=>0];$lbs=(float)($r['LBs Received']??0);$cost=ct_total_cost($r);if(!isset($groups[$k]['months'][$m]))$groups[$k]['months'][$m]=['lbs'=>0,'cost'=>0];$groups[$k]['months'][$m]['lbs']+=$lbs;$groups[$k]['months'][$m]['cost']+=$cost;if($groups[$k]['latest_date']===null||$d>$groups[$k]['latest_date']){$groups[$k]['latest_date']=$d;$groups[$k]['latest_cost']=ct_cost_lb($r);}}
$q=trim($_GET['q']??'');$supplier=trim($_GET['supplier']??'');$sort=$_GET['sort']??'change';$suppliers=[];$rows=[];foreach($groups as $g){$suppliers[$g['supplier']]=1;if($q!==''&&!ld_contains($g['supplier'],$q)&&!ld_contains($g['product'],$q))continue;if($supplier!==''&&$g['supplier']!==$supplier)continue;$lbs3=$cost3=$lbs12=$cost12=0;foreach($months as $i=>$m){$x=$g['months'][$m]??['lbs'=>0,'cost'=>0];if($i<3){$lbs3+=$x['lbs'];$cost3+=$x['cost'];}if($i<12){$lbs12+=$x['lbs'];$cost12+=$x['cost'];}}$avg3=$lbs3?($cost3/$lbs3):0;$avg12=$lbs12?($cost12/$lbs12):0;$chg=$avg12?($g['latest_cost']/$avg12-1):0;$g['_avg3']=$avg3;$g['_avg12']=$avg12;$g['_chg']=$chg;$g['_lbs12']=$lbs12;$rows[]=$g;}ksort($suppliers,SORT_NATURAL|SORT_FLAG_CASE);usort($rows,function($a,$b)use($sort){if($sort==='supplier')return strcasecmp($a['supplier'],$b['supplier'])?:strcasecmp($a['product'],$b['product']);if($sort==='volume')return $b['_lbs12']<=>$a['_lbs12'];if($sort==='latest')return $b['latest_cost']<=>$a['latest_cost'];return abs($b['_chg'])<=>abs($a['_chg']);});$up=count(array_filter($rows,fn($r)=>$r['_chg']>.05));$down=count(array_filter($rows,fn($r)=>$r['_chg']<-.05));$export=$rows;
ld_head('Purchase Cost Trend','Weighted average purchase cost by supplier and product over the last 13 months');?>
<div class="cards"><div class="card"><div class="n"><?=count($rows)?></div><div class="l">Supplier / Product Pairs</div></div><div class="card"><div class="n"><?=$up?></div><div class="l">Cost Up >5%</div></div><div class="card"><div class="n"><?=$down?></div><div class="l">Cost Down >5%</div></div><div class="card"><div class="n"><?=ld_n(array_sum(array_column($rows,'_lbs12')))?> lb</div><div class="l">Trailing 12-Month Purchase Volume</div></div></div>
<section class="panel"><form class="filters"><div class="field wide"><label>Supplier / Product</label><input name="q" value="<?=ct_h($q)?>"></div><div class="field"><label>Supplier</label><select name="supplier"><option value="">All suppliers</option><?php foreach($suppliers as $s=>$x):?><option value="<?=ct_h($s)?>" <?=$supplier===$s?'selected':''?>><?=ct_h($s)?></option><?php endforeach;?></select></div><div class="field"><label>Sort</label><select name="sort"><option value="change" <?=$sort==='change'?'selected':''?>>Largest cost change</option><option value="volume" <?=$sort==='volume'?'selected':''?>>12-mo volume</option><option value="latest" <?=$sort==='latest'?'selected':''?>>Latest cost</option><option value="supplier" <?=$sort==='supplier'?'selected':''?>>Supplier</option></select></div><button class="btn">Run</button><a class="btn alt" href="cost-trend.php">Reset</a><button class="btn green" type="button" id="xlsxBtn">Download .xlsx</button></form></section>
<div class="tablewrap"><table><thead><tr><th class="left">Supplier</th><th class="left prod">Product</th><th>Latest Cost/LB</th><th>3-Mo Avg</th><th>12-Mo Avg</th><th>Change vs 12-Mo</th><?php foreach($months as $m):?><th><?=ct_ml($m)?></th><?php endforeach;?><th>12-Mo Volume</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td class="left"><?=ct_h($r['supplier'])?></td><td class="left prod"><?=ct_h($r['product'])?></td><td><?=ld_money($r['latest_cost'],4)?></td><td><?=ld_money($r['_avg3'],4)?></td><td><?=ld_money($r['_avg12'],4)?></td><td class="<?=$r['_chg']>0?'neg':($r['_chg']<0?'pos':'')?>"><?=number_format($r['_chg']*100,1)?>%</td><?php foreach($months as $m):$x=$r['months'][$m]??['lbs'=>0,'cost'=>0];$avg=$x['lbs']?($x['cost']/$x['lbs']):0;?><td><?=$avg?ld_money($avg,4):'-'?></td><?php endforeach;?><td><?=ld_n($r['_lbs12'])?></td></tr><?php endforeach;?></tbody></table></div><div class="foot">Monthly cost is weighted average Total Item Cost / LBs Received. Latest Cost/LB is derived from receipt dollars divided by receipt pounds when the source workbook does not provide Cost/LB.</div>
<script src="https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js"></script><script>const rows=<?=json_encode($export,JSON_UNESCAPED_UNICODE)?>,months=<?=json_encode($months)?>,labels=<?=json_encode(array_map('ct_ml',$months))?>;document.getElementById('xlsxBtn').onclick=async()=>{if(!window.ExcelJS)return alert('Excel library could not load.');const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Cost Trend');const h=['Supplier','Product','Latest Cost/LB','3-Mo Avg','12-Mo Avg','Change vs 12-Mo',...labels,'12-Mo Volume'];ws.addRow(h);rows.forEach(r=>ws.addRow([r.supplier,r.product,r.latest_cost,r._avg3,r._avg12,r._chg,...months.map(m=>{let x=r.months[m]||{lbs:0,cost:0};return x.lbs?x.cost/x.lbs:0}),r._lbs12]));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF061D3F'}};ws.views=[{state:'frozen',ySplit:1,xSplit:2}];ws.autoFilter={from:'A1',to:{row:1,column:h.length}};ws.getColumn(1).width=28;ws.getColumn(2).width=38;for(let c=3;c<=h.length;c++)ws.getColumn(c).width=13;for(let r=2;r<=ws.rowCount;r++){for(let c=3;c<h.length;c++)ws.getCell(r,c).numFmt=c===6?'0.0%':'$0.0000';ws.getCell(r,h.length).numFmt='#,##0';}const b=await wb.xlsx.writeBuffer(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([b]));a.download='Lowe_Purchase_Cost_Trend_<?=date('Y-m-d')?>.xlsx';a.click();URL.revokeObjectURL(a.href);};</script><?php ld_foot(); ?>
