<?php
declare(strict_types=1);require_once __DIR__.'/inventory-model.php';
$q=trim((string)($_GET['q']??''));$view=(string)($_GET['view']??'all');$supplier=trim((string)($_GET['supplier']??''));$rows=[];$sup=[];
foreach($data['rows'] as $r){if(($r['primary_supplier']??'')!=='')$sup[$r['primary_supplier']]=true;$risk=$r['projected_shortage_lbs']>0.5||$r['available_lbs']<0||$r['expired_lbs']>0;if(!$risk)continue;if($q!==''&&!ld_contains($r['product_name'],$q)&&!ld_contains($r['product_code'],$q)&&!ld_contains($r['top_customer'],$q))continue;if($supplier!==''&&$r['primary_supplier']!==$supplier)continue;if($view==='shortage'&&$r['projected_shortage_lbs']<=0.5)continue;if($view==='negative'&&$r['available_lbs']>=0)continue;if($view==='expiry'&&$r['expired_lbs']<=0&&$r['expiring_90_lbs']<=0)continue;$rows[]=$r;}usort($rows,fn($a,$b)=>$b['projected_shortage_lbs']<=>$a['projected_shortage_lbs']);ksort($sup,SORT_NATURAL|SORT_FLAG_CASE);
$short=array_sum(array_column($rows,'projected_shortage_lbs'));$so=array_sum(array_column($rows,'open_sales_orders_lbs'));$po=array_sum(array_column($rows,'open_purchase_orders_lbs'));
ld_head('Inventory Risk / Shortage','Products where lot-level supply may not cover commitments and near-term demand');?>
<div class="cards"><div class="card"><div class="n"><?=count($rows)?></div><div class="l">Products at Risk</div></div><div class="card"><div class="n"><?=ld_n($short)?> lb</div><div class="l">Projected Shortage</div></div><div class="card"><div class="n"><?=ld_n($so)?> lb</div><div class="l">Open Sales Orders</div></div><div class="card"><div class="n"><?=ld_n($po)?> lb</div><div class="l">Inbound PO Supply</div></div></div>
<section class="panel"><form class="filters"><div class="field wide"><label>Product / Code / Customer</label><input name="q" value="<?=ld_h($q)?>"></div><div class="field"><label>View</label><select name="view"><option value="all">All risk items</option><option value="shortage" <?=$view==='shortage'?'selected':''?>>Projected shortage</option><option value="negative" <?=$view==='negative'?'selected':''?>>Negative available</option><option value="expiry" <?=$view==='expiry'?'selected':''?>>Expiry attention</option></select></div><div class="field"><label>Supplier</label><select name="supplier"><option value="">All suppliers</option><?php foreach(array_keys($sup) as $s):?><option value="<?=ld_h($s)?>" <?=$supplier===$s?'selected':''?>><?=ld_h($s)?></option><?php endforeach;?></select></div><button class="btn">Run</button><a class="btn alt" href="inventory-risk.php">Reset</a></form></section>
<div class="tablewrap"><table><thead><tr><th class="left">Product #</th><th class="left prod">Product</th><th>On Hand</th><th>Open SO</th><th>Available</th><th>Open PO</th><th>Projected Available</th><th>Forecast 30D</th><th>Projected Shortage</th><th>Days Supply</th><th>Recommended Buy</th><th>Expired LB</th><th>Expiring 90D LB</th><th class="left">Supplier</th><th class="left">Top Customer</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="15" style="text-align:center;padding:28px">No risk items match these filters.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td class="left"><?=ld_h($r['product_code'])?></td><td class="left prod"><?=ld_h($r['product_name'])?></td><td><?=ld_n($r['on_hand_lbs'])?></td><td><?=ld_n($r['open_sales_orders_lbs'])?></td><td class="<?=$r['available_lbs']<0?'neg':''?>"><?=ld_n($r['available_lbs'])?></td><td><?=ld_n($r['open_purchase_orders_lbs'])?></td><td class="<?=$r['projected_available_lbs']<0?'neg':''?>"><?=ld_n($r['projected_available_lbs'])?></td><td><?=ld_n($r['forecast_next_30_days_lbs'])?></td><td class="<?=$r['projected_shortage_lbs']>0?'neg':''?>"><?=ld_n($r['projected_shortage_lbs'])?></td><td><?=$r['days_supply_after_open_so']===null?'-':ld_n($r['days_supply_after_open_so'],1)?></td><td><?=ld_n($r['recommended_order_lbs'])?></td><td class="<?=$r['expired_lbs']>0?'neg':''?>"><?=ld_n($r['expired_lbs'])?></td><td class="<?=$r['expiring_90_lbs']>0?'soon':''?>"><?=ld_n($r['expiring_90_lbs'])?></td><td class="left"><?=ld_h($r['primary_supplier'])?></td><td class="left"><?=ld_h($r['top_customer'])?></td></tr><?php endforeach;?></tbody></table></div><div class="foot">Projected shortage = Forecast 30D - (On Hand - Open SO + Open PO), floored at zero. Expiry risk is calculated directly from lot-level Expire Date and remaining Total LBs.</div><?php ld_foot(); ?>
