<?php
declare(strict_types=1);
require_once __DIR__ . '/predictive-order-engine.php';
function ld_h($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ld_n($v,$d=0):string{return number_format((float)$v,$d);}
function ld_money($v,$d=0):string{return '$'.number_format((float)$v,$d);}
function ld_master():string{foreach([__DIR__.'/predictive-order-files/Lowe-Master-Latest.xlsx',__DIR__.'/Lowe Master.xlsx',__DIR__.'/Lowe-Master-Latest.xlsx'] as $p)if(is_file($p))return $p; throw new RuntimeException('Lowe Master workbook not found. Upload it from predictive-orders-admin.php.');}
function ld_rows(string $sheet):array{return of_assoc(of_read_sheet(ld_master(),$sheet));}
function ld_key($v):string{return strtoupper(trim(preg_replace('/\s+/',' ',(string)$v)));}
function ld_contains($a,$b):bool{return $b===''||stripos((string)$a,(string)$b)!==false;}
function ld_nav():string{return '<a class="workflow-link" href="salesworkflow.php">Back to Sales Workflow</a>';}
function ld_head(string $title,string $sub):void{echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>'.ld_h($title).' | Lowe Chemical</title><style>'.ld_css().'</style></head><body><header><div class="head"><div class="brand"><img src="/images/lowe-logo.png" alt="Lowe Chemical"><div><h1>'.ld_h($title).'</h1><p>'.ld_h($sub).'</p></div></div>'.ld_nav().'</div></header><main>';}
function ld_foot():void{echo '</main></body></html>';}
function ld_css():string{return ':root{--n:#061d3f;--r:#c8102e;--g:#15803d;--o:#d97706;--bg:#f3f5f8;--ln:#d8e0e8;--mut:#68788b}*{box-sizing:border-box}body{margin:0;background:var(--bg);font-family:Arial,sans-serif;color:#1f2d3d;font-size:13px}header{background:var(--n);border-bottom:4px solid var(--r);color:#fff}.head{max-width:1700px;margin:auto;padding:14px 18px;display:flex;align-items:center;justify-content:space-between;gap:15px}.brand{display:flex;align-items:center;gap:14px}.brand img{width:165px;background:#fff;border-radius:6px;padding:6px 9px}.brand h1{margin:0;font-size:23px}.brand p{margin:4px 0 0;color:#cbd8e8}.workflow-link,.btn{display:inline-block;padding:9px 13px;border-radius:6px;text-decoration:none;font-weight:700;border:0;cursor:pointer}.workflow-link{background:#fff;color:var(--n)}.btn{background:var(--r);color:#fff}.btn.alt{background:#56667a}.btn.green{background:var(--g)}main{max-width:1700px;margin:16px auto;padding:0 14px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.card,.panel{background:#fff;border:1px solid var(--ln);border-radius:8px}.card{padding:12px;border-left:5px solid #1d5e91}.card .n{font-size:22px;font-weight:800;color:var(--n)}.card .l{font-size:10px;text-transform:uppercase;color:var(--mut);margin-top:3px}.panel{padding:12px;margin-bottom:12px}.filters{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.field{min-width:150px}.field.wide{min-width:260px}.field label{display:block;font-size:10px;text-transform:uppercase;font-weight:700;color:var(--mut);margin-bottom:3px}.field input,.field select{width:100%;padding:8px;border:1px solid #b9c5d1;border-radius:5px;background:#fff}.tablewrap{overflow:auto;border:1px solid var(--ln);border-radius:7px;max-height:72vh}table{border-collapse:collapse;width:max-content;min-width:100%;background:#fff}th,td{border:1px solid #d8e0e8;padding:7px 8px;white-space:nowrap;text-align:right}th{position:sticky;top:0;background:#e9eef4;color:var(--n);z-index:2;font-size:10px;text-transform:uppercase}th.left,td.left{text-align:left}.prod{white-space:normal;min-width:250px;max-width:330px}.action{font-weight:800}.now{color:#a61b1b}.soon{color:#b45309}.plan{color:#1d5e91}.ok{color:var(--g)}.neg{color:#a61b1b;font-weight:800}.pos{color:var(--g);font-weight:800}.muted{color:var(--mut)}.foot{font-size:11px;color:var(--mut);margin-top:8px}.pill{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef2f7;font-weight:700}.right{text-align:right}@media(max-width:850px){.cards{grid-template-columns:1fr 1fr}.head{display:block}.workflow-link{margin-top:10px}.filters{display:grid;grid-template-columns:1fr 1fr}.field,.field.wide{min-width:0}.tablewrap{max-height:none}.brand img{width:135px}.brand h1{font-size:19px}}@media(max-width:520px){.cards,.filters{grid-template-columns:1fr}.brand{display:block}.brand img{margin-bottom:8px}main{padding:0 7px}.tablewrap{overflow:auto}}';}
function ld_export_csv(string $name,array $headers,array $rows):void{header('Content-Type:text/csv');header('Content-Disposition:attachment; filename="'.$name.'"');$f=fopen('php://output','w');fputcsv($f,$headers);foreach($rows as $r)fputcsv($f,$r);fclose($f);exit;}
function ld_predictive():array{$p=__DIR__.'/predictive-order-data.json';if(!is_file($p))throw new RuntimeException('predictive-order-data.json not found. Update Predictive Order Data first.');$d=json_decode((string)file_get_contents($p),true);if(!is_array($d)||empty($d['rows']))throw new RuntimeException('Predictive order data is empty.');return $d;}
?>
