<?php
declare(strict_types=1);
require_once __DIR__.'/inventory-model-v2.php';
if (!defined('LOWE_INVENTORY_MODEL_VERSION') || LOWE_INVENTORY_MODEL_VERSION < 2) {
    http_response_code(500);
    die('The lot-level inventory model is not installed. Upload inventory-model-v2.php with this dashboard.');
}
function md_h($v):string{return ld_h($v);}function md_d($v):string{$t=strtotime((string)$v);return$t?date('M j, Y',$t):'-';}function md_pct($v):string{return number_format((float)$v*100,1).'%';}function md_key($v):string{return strtoupper(trim(preg_replace('/\s+/',' ',(string)$v)));}function md_id($a,$b):string{$a=trim((string)$a);return md_key($a!==''?$a:$b);}
try{$inv=ld_rows('Invoices');$pur=ld_rows('Purchases');$so=ld_rows('Open Sales Orders');$po=ld_rows('Open Purchase Orders');$stock=ld_rows('Inventory');}catch(Throwable $e){die(md_h($e->getMessage()));}
$latestInvoice=$data['as_of']??date('Y-m-d');$cut=new DateTimeImmutable($latestInvoice);$cy=(int)$cut->format('Y');$py=$cy-1;$y0="$cy-01-01";$y1=$cut->format('Y-m-d');$p0="$py-01-01";$p1=$cut->modify('-1 year')->format('Y-m-d');$today=new DateTimeImmutable(date('Y-m-d'));
$firstCust=[];foreach($inv as $r){if(strtolower(trim((string)($r['Doc Type']??'')))!=='invoiced')continue;$d=of_date($r['INV. Date']??'');$c=trim((string)($r['Cust Name']??''));if(!$d||$c==='')continue;$k=md_id($r['Cust#']??'',$c);if(!isset($firstCust[$k])||$d<$firstCust[$k])$firstCust[$k]=$d;}
$firstSup=[];foreach($pur as $r){$d=of_date($r['Receipt Date']??'');$s=trim((string)($r['Supplier Name']??''));if(!$d||$s==='')continue;$k=md_id($r['Supplier Number']??'',$s);if(!isset($firstSup[$k])||$d<$firstSup[$k])$firstSup[$k]=$d;}
function md_sales(array $rows,string $from,string $to,array $first,bool $new):array{$m=['sales'=>0.0,'profit'=>0.0,'lbs'=>0.0,'inv'=>[],'cr'=>[],'cust'=>[],'prod'=>[],'codes'=>[],'new'=>[]];foreach($rows as $r){$d=of_date($r['INV. Date']??'');if(!$d||$d<$from||$d>$to)continue;$t=strtolower(trim((string)($r['Doc Type']??'')));if(!in_array($t,['invoiced','credit'],true))continue;$n=trim((string)($r['INV#']??''));if($n!=='')$m[$t==='invoiced'?'inv':'cr'][$n]=true;$m['sales']+=of_num($r['Sales $$']??0);$m['profit']+=of_num($r['Profit $$']??0);$m['lbs']+=of_num($r['LBS']??0);$c=trim((string)($r['Cust Name']??''));if($c!==''){$k=md_id($r['Cust#']??'',$c);$m['cust'][$k]=true;if($new&&isset($first[$k])&&$first[$k]>=$from&&$first[$k]<=$to)$m['new'][$k]=true;}$p=trim((string)($r['Product Name']??''));if($p!=='')$m['prod'][md_key($p)]=true;$pc=trim((string)($r['Product Number']??''));if($pc!=='')$m['codes'][md_key($pc)]=true;}return['sales'=>$m['sales'],'profit'=>$m['profit'],'lbs'=>$m['lbs'],'invoice_count'=>count($m['inv']),'credit_count'=>count($m['cr']),'customer_count'=>count($m['cust']),'product_count'=>count($m['prod']),'product_code_count'=>count($m['codes']),'new_customer_count'=>count($m['new']),'gp_pct'=>abs($m['sales'])>0.001?$m['profit']/$m['sales']:0,'avg_invoice_sales'=>count($m['inv'])?$m['sales']/count($m['inv']):0,'profit_per_lb'=>abs($m['lbs'])>0.001?$m['profit']/$m['lbs']:0];}
function md_purchases(array $rows,string $from,string $to,array $first):array{$sp=0;$lbs=0;$pos=[];$sup=[];$prod=[];$codes=[];$new=[];foreach($rows as $r){$d=of_date($r['Receipt Date']??'');if(!$d||$d<$from||$d>$to)continue;$sp+=of_num($r['Total Item Cost']??0);$lbs+=of_num($r['LBs Received']??0);$pn=trim((string)($r['PO Number']??''));if($pn!=='')$pos[$pn]=true;$s=trim((string)($r['Supplier Name']??''));if($s!==''){$k=md_id($r['Supplier Number']??'',$s);$sup[$k]=true;if(isset($first[$k])&&$first[$k]>=$from&&$first[$k]<=$to)$new[$k]=true;}$p=trim((string)($r['Product Name']??''));if($p!=='')$prod[md_key($p)]=true;$pc=trim((string)($r['Product Number']??''));if($pc!=='')$codes[md_key($pc)]=true;}return['spend'=>$sp,'lbs'=>$lbs,'po_count'=>count($pos),'supplier_count'=>count($sup),'product_count'=>count($prod),'product_code_count'=>count($codes),'new_supplier_count'=>count($new)];}
$ys=md_sales($inv,$y0,$y1,$firstCust,true);$ps=md_sales($inv,$p0,$p1,$firstCust,false);$yp=md_purchases($pur,$y0,$y1,$firstSup);$pp=md_purchases($pur,$p0,$p1,$firstSup);
// YTD/PYTD visual comparison data.
$monthly=array_fill(1,12,['ytd'=>0.0,'pytd'=>0.0]);
$customerMove=[];
foreach($inv as $r){
    $d=of_date($r['INV. Date']??'');$t=strtolower(trim((string)($r['Doc Type']??'')));
    if(!$d||!in_array($t,['invoiced','credit'],true))continue;
    $sales=of_num($r['Sales $$']??0);$c=trim((string)($r['Cust Name']??''));$ck=$c!==''?md_id($r['Cust#']??'',$c):'';
    if($d>=$y0&&$d<=$y1){$m=(int)substr($d,5,2);$monthly[$m]['ytd']+=$sales;if($ck!==''){$customerMove[$ck]['name']=$c;$customerMove[$ck]['ytd']=($customerMove[$ck]['ytd']??0)+$sales;}}
    elseif($d>=$p0&&$d<=$p1){$m=(int)substr($d,5,2);$monthly[$m]['pytd']+=$sales;if($ck!==''){$customerMove[$ck]['name']=$c;$customerMove[$ck]['pytd']=($customerMove[$ck]['pytd']??0)+$sales;}}
}
$moveCounts=['New'=>0,'Growing'=>0,'Stable'=>0,'Declining'=>0,'Lost / No YTD'=>0];
foreach($customerMove as $r){$a=(float)($r['ytd']??0);$b=(float)($r['pytd']??0);if($a>0&&$b<=0)$cat='New';elseif($a<=0&&$b>0)$cat='Lost / No YTD';elseif($b>0){$pct=($a-$b)/abs($b);$cat=$pct>=.05?'Growing':($pct<=-.05?'Declining':'Stable');}else continue;$moveCounts[$cat]++;}
$perf=[
 ['label'=>'Sales','ytd'=>$ys['sales'],'pytd'=>$ps['sales'],'fmt'=>'money'],
 ['label'=>'Gross Profit','ytd'=>$ys['profit'],'pytd'=>$ps['profit'],'fmt'=>'money'],
 ['label'=>'Pounds','ytd'=>$ys['lbs'],'pytd'=>$ps['lbs'],'fmt'=>'number'],
 ['label'=>'Invoices','ytd'=>$ys['invoice_count'],'pytd'=>$ps['invoice_count'],'fmt'=>'number'],
 ['label'=>'Customers','ytd'=>$ys['customer_count'],'pytd'=>$ps['customer_count'],'fmt'=>'number'],
 ['label'=>'Products','ytd'=>$ys['product_count'],'pytd'=>$ps['product_count'],'fmt'=>'number']
];

// Exact lot-level inventory aging from the revised Inventory tab.
$aging=array_fill_keys(['1-30','31-60','61-90','91-180','181-365','365+'],['value'=>0.0,'lbs'=>0.0,'lots'=>0]);$invTotals=['value'=>0.0,'lbs'=>0.0,'products'=>[],'codes'=>[],'lots'=>0,'expired'=>0.0,'exp90'=>0.0];
foreach($stock as $r){$lbs=of_num($r['Total LBs']??0);$val=of_num($r['Total Cost']??0);if($lbs<=0.00001&&$val<=0.00001)continue;$invTotals['lbs']+=$lbs;$invTotals['value']+=$val;$invTotals['lots']++;$pc=trim((string)($r['Product Number']??''));if($pc!=='')$invTotals['codes'][md_key($pc)]=true;$pn=trim((string)($r['Product Name']??''));if($pn!=='')$invTotals['products'][md_key($pn)]=true;$rd=of_date($r['Receipt Date']??'');$days=$rd?max(0,(int)(new DateTimeImmutable($rd))->diff($today)->format('%a')):0;if($days<=30)$b='1-30';elseif($days<=60)$b='31-60';elseif($days<=90)$b='61-90';elseif($days<=180)$b='91-180';elseif($days<=365)$b='181-365';else$b='365+';$aging[$b]['value']+=$val;$aging[$b]['lbs']+=$lbs;$aging[$b]['lots']++;$ed=of_date($r['Expire Date']??'');if($ed){$dd=(int)$today->diff(new DateTimeImmutable($ed))->format('%r%a');if($dd<0)$invTotals['expired']+=$lbs;elseif($dd<=90)$invTotals['exp90']+=$lbs;}}
$invTotals['product_count']=count($invTotals['products']);$invTotals['code_count']=count($invTotals['codes']);
$neg=count(array_filter($data['rows'],fn($r)=>$r['available_lbs']<0));$orderNow=count(array_filter($data['rows'],fn($r)=>$r['action']==='ORDER NOW'));$short=count(array_filter($data['rows'],fn($r)=>$r['projected_shortage_lbs']>0.5));$belowMin=count(array_filter($data['rows'],fn($r)=>$r['min_lbs']>0&&$r['projected_available_lbs']<$r['min_lbs']));$aboveMax=count(array_filter($data['rows'],fn($r)=>$r['max_lbs']>0&&$r['on_hand_lbs']>$r['max_lbs']));
$os=['orders'=>[],'cust'=>[],'prod'=>[],'codes'=>[],'sales'=>0.0,'lbs'=>0.0,'past'=>0];foreach($so as $r){$o=trim((string)($r['Order #']??''));if($o!=='')$os['orders'][$o]=true;$c=trim((string)($r['Customer Name']??''));if($c!=='')$os['cust'][md_id($r['Customer Number']??'',$c)]=true;$p=trim((string)($r['Product Name']??''));if($p!=='')$os['prod'][md_key($p)]=true;$pc=trim((string)($r['Product Number']??''));if($pc!=='')$os['codes'][md_key($pc)]=true;$os['sales']+=of_num($r['Total $$']??0);$os['lbs']+=of_num($r['Total LBS']??0);$sd=of_date($r['Ship Date']??'');if($sd&&$sd<date('Y-m-d'))$os['past']++;}
$op=['pos'=>[],'sup'=>[],'prod'=>[],'codes'=>[],'lbs'=>0.0,'spend'=>0.0,'old'=>[]];foreach($po as $r){$n=trim((string)($r['PO Number']??''));if($n!=='')$op['pos'][$n]=true;$s=trim((string)($r['Supplier Name']??''));if($s!=='')$op['sup'][md_id($r['Supplier Number']??'',$s)]=true;$p=trim((string)($r['Product Name']??''));if($p!=='')$op['prod'][md_key($p)]=true;$pc=trim((string)($r['Product Number']??''));if($pc!=='')$op['codes'][md_key($pc)]=true;$op['lbs']+=of_num($r['LBS']??0);$op['spend']+=of_num($r['Total Cost']??0);$d=of_date($r['PO Date']??'');if($n!==''&&$d&&max(0,(int)(new DateTimeImmutable($d))->diff($today)->format('%a'))>30)$op['old'][$n]=true;}
// Largest negative customer/product sales variances.
$g=[];foreach($inv as $r){$d=of_date($r['INV. Date']??'');$t=strtolower(trim((string)($r['Doc Type']??'')));if(!$d||!in_array($t,['invoiced','credit'],true))continue;$per=($d>=$y0&&$d<=$y1)?'ytd':(($d>=$p0&&$d<=$p1)?'pytd':null);if(!$per)continue;$c=trim((string)($r['Cust Name']??''));$p=trim((string)($r['Product Name']??''));if($c===''||$p==='')continue;$k=md_key($c).'|'.md_key($p);if(!isset($g[$k]))$g[$k]=['customer'=>$c,'product'=>$p,'ytd'=>0.0,'pytd'=>0.0];$g[$k][$per]+=of_num($r['Sales $$']??0);} $decl=[];foreach($g as $r){$r['variance']=$r['ytd']-$r['pytd'];if($r['variance']<0)$decl[]=$r;}usort($decl,fn($a,$b)=>$a['variance']<=>$b['variance']);$decl=array_slice($decl,0,10);
ld_head('Management Dashboard','Executive operating view: sales, purchasing, inventory, and open commitments');?>
<style>
.md-section,.section-card{margin-bottom:18px}.md-section,.section-card,.compare{scroll-margin-top:14px}
.md-title{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:0 0 10px;padding:9px 12px;border-radius:8px;border-left:7px solid #1d5e91;background:#eef4fb}
.md-title h2{margin:0;color:#061d3f;font-size:18px}.md-title .sub{font-size:11px;color:#68788b}
.band-sales .md-title{border-left-color:#1d5e91;background:#eef4fb}.band-prior .md-title{border-left-color:#64748b;background:#f1f5f9}.band-variance .md-title{border-left-color:#7c3aed;background:#f5f0ff}.band-inventory .md-title{border-left-color:#d97706;background:#fff7e8}
.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.metric{background:#fff;border:1px solid #d8e0e8;border-radius:7px;padding:10px 11px}.metric .v{font-size:19px;font-weight:800;color:#061d3f}.metric .k{font-size:9.5px;text-transform:uppercase;color:#68788b;margin-top:3px}.metric.green .v{color:#15803d}.metric.red .v{color:#a61b1b}.metric.orange .v{color:#b45309}
.compare{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:18px}.age-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:7px}.age{background:#fff;border:1px solid #d8e0e8;border-radius:7px;padding:10px}.age .v{font-size:17px;font-weight:800;color:#061d3f}.age .k{font-size:9.5px;text-transform:uppercase;color:#68788b}.age .s{font-size:10px;color:#68788b;margin-top:5px}
.section-card{background:#fff;border:1px solid #d8e0e8;border-radius:9px;padding:12px;border-top:6px solid #94a3b8}.section-card h3{margin:0 0 10px;color:#061d3f;font-size:15px}.purchase-card{border-top-color:#15803d}.sales-order-card{border-top-color:#0891b2}.purchase-order-card{border-top-color:#16a34a}.risk-card{border-top-color:#c8102e}.reports-card{border-top-color:#061d3f}
.section-separator{height:0;border:0;border-top:4px solid #d8e0e8;margin:24px 0 18px}.sep-sales{border-color:#1d5e91}.sep-purchase{border-color:#15803d}.sep-inventory{border-color:#d97706}.sep-commitments{border-color:#0891b2}.sep-risk{border-color:#c8102e}
.chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0 20px}.chart-card{background:#fff;border:1px solid #d8e0e8;border-top:6px solid #d97706;border-radius:9px;padding:13px;min-height:330px}.chart-card h3{margin:0 0 3px;color:#061d3f;font-size:15px}.chart-card p{margin:0 0 12px;color:#68788b;font-size:11px}.chart-flex{display:flex;align-items:center;gap:18px;min-height:250px}.pie{width:230px;height:230px;border-radius:50%;flex:0 0 230px;box-shadow:inset 0 0 0 1px #d8e0e8}.legend{display:grid;gap:8px;min-width:0}.legend-row{display:grid;grid-template-columns:14px minmax(90px,1fr) auto;gap:8px;align-items:center;font-size:11px;color:#344454}.legend-swatch{width:12px;height:12px;border-radius:2px}.legend-label{white-space:nowrap}.legend-value{font-weight:800;color:#061d3f;text-align:right;white-space:nowrap}.chart-empty{display:flex;align-items:center;justify-content:center;width:230px;height:230px;border-radius:50%;background:#eef2f6;color:#68788b;font-size:12px;font-weight:700;text-align:center;padding:20px}
.links{display:flex;gap:7px;flex-wrap:wrap}.note{background:#fff8e7;border-left:4px solid #d97706;padding:10px 12px;border-radius:6px;font-size:11px;color:#5b6570;line-height:1.45;margin-bottom:14px}.delta-pos{color:#15803d;font-weight:800}.delta-neg{color:#a61b1b;font-weight:800}
.yoy-visuals{display:grid;grid-template-columns:1.15fr .85fr;gap:12px;margin:12px 0 18px}.visual-card{background:#fff;border:1px solid #d8e0e8;border-radius:10px;padding:14px}.visual-card h3{margin:0 0 4px;color:#061d3f;font-size:15px}.visual-card .desc{font-size:10px;color:#68788b;margin-bottom:12px}.perf-row{display:grid;grid-template-columns:105px 1fr 1fr;gap:8px;align-items:center;margin:8px 0}.perf-label{font-size:11px;font-weight:800;color:#334155}.barbox{height:25px;background:#eef2f6;border-radius:5px;overflow:hidden;position:relative}.barfill{height:100%;min-width:2px}.bar-ytd{background:#1d5e91}.bar-pytd{background:#94a3b8}.bartext{position:absolute;inset:0;display:flex;align-items:center;padding:0 7px;font-size:10px;font-weight:800;color:#0f172a}.legend-inline{display:flex;gap:15px;font-size:10px;color:#64748b;margin-bottom:8px}.dot{display:inline-block;width:9px;height:9px;border-radius:2px;margin-right:4px}.monthly-chart{display:flex;align-items:flex-end;gap:7px;height:210px;border-bottom:1px solid #cbd5e1;padding:0 4px}.month-col{flex:1;height:100%;display:flex;align-items:flex-end;justify-content:center;gap:2px;position:relative;padding-bottom:22px}.mbar{width:38%;min-height:1px;border-radius:3px 3px 0 0}.mlabel{position:absolute;bottom:2px;font-size:9px;color:#64748b}.movement{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.move{border-radius:8px;padding:12px 8px;text-align:center;background:#f8fafc;border:1px solid #e2e8f0}.move strong{display:block;font-size:23px;color:#061d3f}.move span{font-size:9px;text-transform:uppercase;color:#64748b}.move.new{border-top:5px solid #2563eb}.move.grow{border-top:5px solid #16a34a}.move.stable{border-top:5px solid #64748b}.move.decline{border-top:5px solid #f59e0b}.move.lost{border-top:5px solid #dc2626}

@media(max-width:1100px){.metric-grid{grid-template-columns:repeat(2,1fr)}.age-grid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:700px){.compare,.chart-grid{grid-template-columns:1fr}.metric-grid,.age-grid{grid-template-columns:1fr 1fr}.chart-flex{flex-direction:column;align-items:flex-start}.pie,.chart-empty{width:210px;height:210px;flex-basis:210px}.legend{width:100%}}
@media(max-width:430px){.metric-grid,.age-grid{grid-template-columns:1fr}}
</style>
<div class="note"><strong>Data notes:</strong> inventory value and aging now come directly from current lot-level Inventory rows using Total Cost, Total LBs and Receipt Date. Historical purchase activity is still dated by Receipt Date, so YTD/PYTD PO counts mean POs with receipts in the period. MIN/MAX and Lead Time are used where populated; blank/zero policy fields are not inferred.</div>
<?php $sections=[[$cy.' YTD Sales',$ys,true],[$py.' PYTD Sales',$ps,false]];foreach($sections as [$ttl,$m,$isY]):?><section class="md-section <?=$isY?'band-sales':'band-prior'?>"><div class="md-title"><h2><?=$ttl?></h2><div class="sub">Through <?=md_d($isY?$y1:$p1)?></div></div><div class="metric-grid"><div class="metric"><div class="v"><?=ld_money($m['sales'])?></div><div class="k">Sales</div></div><div class="metric"><div class="v"><?=ld_money($m['profit'])?></div><div class="k">Gross Profit - <?=md_pct($m['gp_pct'])?> GP</div></div><div class="metric"><div class="v"><?=ld_n($m['lbs'])?> lb</div><div class="k">Pounds Shipped</div></div><div class="metric"><div class="v"><?=ld_n($m['invoice_count'])?></div><div class="k">Invoices</div></div><div class="metric"><div class="v"><?=ld_n($m['credit_count'])?></div><div class="k">Credits</div></div><div class="metric"><div class="v"><?=ld_n($m['customer_count'])?></div><div class="k">Customers Invoiced</div></div><div class="metric"><div class="v"><?=ld_n($m['product_count'])?></div><div class="k">Unique Products</div></div><div class="metric"><div class="v"><?=ld_n($m['product_code_count'])?></div><div class="k">Unique Product Codes</div></div><?php if($isY):?><div class="metric green"><div class="v"><?=ld_n($m['new_customer_count'])?></div><div class="k">New Customers</div></div><?php endif;?><div class="metric"><div class="v"><?=ld_money($m['avg_invoice_sales'])?></div><div class="k">Avg Sales / Invoice</div></div><div class="metric"><div class="v"><?=ld_money($m['profit_per_lb'],2)?></div><div class="k">Profit / LB</div></div></div></section><?php endforeach;?>
<hr class="section-separator sep-sales"><?php $sv=$ys['sales']-$ps['sales'];$pv=$ys['profit']-$ps['profit'];$lv=$ys['lbs']-$ps['lbs'];?><section class="md-section band-variance"><div class="md-title"><h2>YTD Sales Variance</h2></div><div class="metric-grid"><div class="metric"><div class="v <?=$sv>=0?'delta-pos':'delta-neg'?>"><?=($sv>=0?'+':'').ld_money($sv)?></div><div class="k">Sales Variance</div></div><div class="metric"><div class="v <?=$pv>=0?'delta-pos':'delta-neg'?>"><?=($pv>=0?'+':'').ld_money($pv)?></div><div class="k">Profit Variance</div></div><div class="metric"><div class="v <?=$lv>=0?'delta-pos':'delta-neg'?>"><?=($lv>=0?'+':'').ld_n($lv)?> lb</div><div class="k">Pounds Variance</div></div></div></section>
<?php
$fmtPerf=function($v,$fmt){return $fmt==='money'?ld_money($v):ld_n($v);};
$monthNames=[1=>'Jan',2=>'Feb',3=>'Mar',4=>'Apr',5=>'May',6=>'Jun',7=>'Jul',8=>'Aug',9=>'Sep',10=>'Oct',11=>'Nov',12=>'Dec'];
$lastMonth=(int)$cut->format('n');$monthMax=1.0;for($m=1;$m<=$lastMonth;$m++)$monthMax=max($monthMax,abs($monthly[$m]['ytd']),abs($monthly[$m]['pytd']));
?>
<section class="md-section band-variance"><div class="md-title"><h2>YTD vs PYTD Visual Comparison</h2><div class="sub"><?=$cy?> through <?=md_d($y1)?> vs <?=$py?> through <?=md_d($p1)?></div></div>
<div class="yoy-visuals">
 <div class="visual-card"><h3>Performance Comparison</h3><div class="desc">Blue = <?=$cy?> YTD · Gray = <?=$py?> PYTD. Each metric is scaled within its own row.</div><div class="legend-inline"><span><i class="dot" style="background:#1d5e91"></i><?=$cy?> YTD</span><span><i class="dot" style="background:#94a3b8"></i><?=$py?> PYTD</span></div>
 <?php foreach($perf as $r):$mx=max(1,abs((float)$r['ytd']),abs((float)$r['pytd']));$yw=min(100,abs((float)$r['ytd'])/$mx*100);$pw=min(100,abs((float)$r['pytd'])/$mx*100);?><div class="perf-row"><div class="perf-label"><?=md_h($r['label'])?></div><div class="barbox"><div class="barfill bar-ytd" style="width:<?=number_format($yw,1,'.','')?>%"></div><div class="bartext"><?=md_h($fmtPerf($r['ytd'],$r['fmt']))?></div></div><div class="barbox"><div class="barfill bar-pytd" style="width:<?=number_format($pw,1,'.','')?>%"></div><div class="bartext"><?=md_h($fmtPerf($r['pytd'],$r['fmt']))?></div></div></div><?php endforeach;?></div>
 <div class="visual-card"><h3>Monthly Sales Trend</h3><div class="desc">Monthly net sales through the current YTD cutoff.</div><div class="legend-inline"><span><i class="dot" style="background:#1d5e91"></i><?=$cy?></span><span><i class="dot" style="background:#94a3b8"></i><?=$py?></span></div><div class="monthly-chart"><?php for($m=1;$m<=$lastMonth;$m++):$yh=max(1,abs($monthly[$m]['ytd'])/$monthMax*165);$ph=max(1,abs($monthly[$m]['pytd'])/$monthMax*165);?><div class="month-col" title="<?=md_h($monthNames[$m])?>: <?=$cy?> <?=md_h(ld_money($monthly[$m]['ytd']))?>; <?=$py?> <?=md_h(ld_money($monthly[$m]['pytd']))?>"><div class="mbar bar-ytd" style="height:<?=number_format($yh,1,'.','')?>px"></div><div class="mbar bar-pytd" style="height:<?=number_format($ph,1,'.','')?>px"></div><div class="mlabel"><?=md_h($monthNames[$m])?></div></div><?php endfor;?></div></div>
</div>
<div class="visual-card"><h3>Customer Business Movement</h3><div class="desc">Customer-level net sales movement versus PYTD. Growing/declining uses a ±5% band; Stable is within ±5%.</div><div class="movement"><div class="move new"><strong><?=$moveCounts['New']?></strong><span>New</span></div><div class="move grow"><strong><?=$moveCounts['Growing']?></strong><span>Growing</span></div><div class="move stable"><strong><?=$moveCounts['Stable']?></strong><span>Stable</span></div><div class="move decline"><strong><?=$moveCounts['Declining']?></strong><span>Declining</span></div><div class="move lost"><strong><?=$moveCounts['Lost / No YTD']?></strong><span>Lost / No YTD</span></div></div></div>
</section>
<hr class="section-separator sep-purchase"><div class="compare"><section class="section-card purchase-card"><h3><?=$cy?> YTD Purchases</h3><div class="metric-grid"><div class="metric"><div class="v"><?=ld_money($yp['spend'])?></div><div class="k">Purchase Spend</div></div><div class="metric"><div class="v"><?=ld_n($yp['po_count'])?></div><div class="k">POs Represented</div></div><div class="metric"><div class="v"><?=ld_n($yp['supplier_count'])?></div><div class="k">Suppliers</div></div><div class="metric"><div class="v"><?=ld_n($yp['product_count'])?></div><div class="k">Unique Products</div></div><div class="metric"><div class="v"><?=ld_n($yp['lbs'])?> lb</div><div class="k">Pounds Purchased</div></div><div class="metric green"><div class="v"><?=ld_n($yp['new_supplier_count'])?></div><div class="k">New Suppliers</div></div></div></section><section class="section-card purchase-card"><h3><?=$py?> PYTD Purchases</h3><div class="metric-grid"><div class="metric"><div class="v"><?=ld_money($pp['spend'])?></div><div class="k">Purchase Spend</div></div><div class="metric"><div class="v"><?=ld_n($pp['po_count'])?></div><div class="k">POs Represented</div></div><div class="metric"><div class="v"><?=ld_n($pp['supplier_count'])?></div><div class="k">Suppliers</div></div><div class="metric"><div class="v"><?=ld_n($pp['product_count'])?></div><div class="k">Unique Products</div></div><div class="metric"><div class="v"><?=ld_n($pp['lbs'])?> lb</div><div class="k">Pounds Purchased</div></div><div class="metric"><div class="v"><?=ld_n($pp['new_supplier_count'])?></div><div class="k">New Suppliers</div></div></div></section></div>
<hr class="section-separator sep-inventory"><section class="md-section band-inventory"><div class="md-title"><h2>Current Inventory</h2><div class="sub">Actual lot-level snapshot</div></div><div class="metric-grid"><div class="metric"><div class="v"><?=ld_n($invTotals['product_count'])?></div><div class="k">Products</div></div><div class="metric"><div class="v"><?=ld_n($invTotals['code_count'])?></div><div class="k">Product Codes</div></div><div class="metric"><div class="v"><?=ld_n($invTotals['lots'])?></div><div class="k">Inventory Lots</div></div><div class="metric"><div class="v"><?=ld_n($invTotals['lbs'])?> lb</div><div class="k">On Hand Pounds</div></div><div class="metric"><div class="v"><?=ld_money($invTotals['value'])?></div><div class="k">Actual Inventory Value</div></div><div class="metric red"><div class="v"><?=$neg?></div><div class="k">Negative Available SKUs</div></div><div class="metric orange"><div class="v"><?=$orderNow?></div><div class="k">Order Now SKUs</div></div><div class="metric red"><div class="v"><?=$short?></div><div class="k">30-Day Shortage SKUs</div></div><div class="metric"><div class="v"><?=$belowMin?></div><div class="k">Below MIN</div></div><div class="metric"><div class="v"><?=$aboveMax?></div><div class="k">Above MAX</div></div><div class="metric red"><div class="v"><?=ld_n($invTotals['expired'])?> lb</div><div class="k">Expired Inventory</div></div><div class="metric orange"><div class="v"><?=ld_n($invTotals['exp90'])?> lb</div><div class="k">Expiring Next 90 Days</div></div></div></section>
<div class="age-grid"><?php foreach($aging as $k=>$a):?><div class="age"><div class="v"><?=ld_money($a['value'])?></div><div class="k"><?=$k?> Days in Stock</div><div class="s"><?=ld_n($a['lbs'])?> lb - <?=ld_n($a['lots'])?> lots</div></div><?php endforeach;?></div>
<?php
$chartColors=['#2563eb','#0ea5e9','#10b981','#f59e0b','#f97316','#dc2626'];
function md_pie_style(array $aging,string $field,array $colors):string{
    $total=0.0;foreach($aging as $a)$total+=(float)($a[$field]??0);if($total<=0)return 'background:#eef2f6';
    $parts=[];$start=0.0;$i=0;foreach($aging as $a){$v=max(0.0,(float)($a[$field]??0));$pct=$total>0?($v/$total*100):0;$end=$start+$pct;$parts[]=$colors[$i%count($colors)].' '.number_format($start,4,'.','').'% '.number_format($end,4,'.','').'%' ;$start=$end;$i++;}
    return 'background:conic-gradient('.implode(',',$parts).')';
}
$valueTotal=array_sum(array_map(fn($a)=>(float)$a['value'],$aging));
$poundTotal=array_sum(array_map(fn($a)=>(float)$a['lbs'],$aging));
?>
<div class="chart-grid">
 <section class="chart-card"><h3>Inventory Value by Age</h3><p>Current inventory value split by days in stock.</p><div class="chart-flex"><?php if($valueTotal>0):?><div class="pie" style="<?=md_h(md_pie_style($aging,'value',$chartColors))?>"></div><?php else:?><div class="chart-empty">No inventory value available</div><?php endif;?><div class="legend"><?php $i=0;foreach($aging as $k=>$a):$pct=$valueTotal>0?((float)$a['value']/$valueTotal*100):0;?><div class="legend-row"><span class="legend-swatch" style="background:<?=md_h($chartColors[$i%count($chartColors)])?>"></span><span class="legend-label"><?=md_h($k)?> days</span><span class="legend-value"><?=ld_money($a['value'])?> · <?=number_format($pct,1)?>%</span></div><?php $i++;endforeach;?></div></div></section>
 <section class="chart-card"><h3>Inventory Pounds by Age</h3><p>Current on-hand pounds split by days in stock.</p><div class="chart-flex"><?php if($poundTotal>0):?><div class="pie" style="<?=md_h(md_pie_style($aging,'lbs',$chartColors))?>"></div><?php else:?><div class="chart-empty">No inventory pounds available</div><?php endif;?><div class="legend"><?php $i=0;foreach($aging as $k=>$a):$pct=$poundTotal>0?((float)$a['lbs']/$poundTotal*100):0;?><div class="legend-row"><span class="legend-swatch" style="background:<?=md_h($chartColors[$i%count($chartColors)])?>"></span><span class="legend-label"><?=md_h($k)?> days</span><span class="legend-value"><?=ld_n($a['lbs'])?> lb · <?=number_format($pct,1)?>%</span></div><?php $i++;endforeach;?></div></div></section>
</div>
<hr class="section-separator sep-commitments"><div class="compare"><section class="section-card sales-order-card"><h3>Open Sales Orders</h3><div class="metric-grid"><div class="metric"><div class="v"><?=count($os['orders'])?></div><div class="k">Open Orders</div></div><div class="metric"><div class="v"><?=ld_money($os['sales'])?></div><div class="k">Sales Dollars</div></div><div class="metric"><div class="v"><?=count($os['cust'])?></div><div class="k">Customers</div></div><div class="metric"><div class="v"><?=ld_n($os['lbs'])?> lb</div><div class="k">Pounds</div></div><div class="metric"><div class="v"><?=count($os['prod'])?></div><div class="k">Products</div></div><div class="metric red"><div class="v"><?=$os['past']?></div><div class="k">Lines Past Ship Date</div></div></div></section><section class="section-card purchase-order-card"><h3>Open Purchase Orders</h3><div class="metric-grid"><div class="metric"><div class="v"><?=count($op['pos'])?></div><div class="k">Open POs</div></div><div class="metric"><div class="v"><?=count($op['sup'])?></div><div class="k">Suppliers</div></div><div class="metric"><div class="v"><?=count($op['prod'])?></div><div class="k">Products</div></div><div class="metric"><div class="v"><?=ld_n($op['lbs'])?> lb</div><div class="k">Pounds</div></div><div class="metric"><div class="v"><?=ld_money($op['spend'])?></div><div class="k">Dollar Value</div></div><div class="metric orange"><div class="v"><?=count($op['old'])?></div><div class="k">POs Older Than 30 Days</div></div></div></section></div>
<hr class="section-separator sep-risk"><section class="md-section section-card risk-card" style="margin-top:14px"><h3>Largest Negative Customer/Product Sales Variances</h3><div class="tablewrap"><table><thead><tr><th class="left">Customer</th><th class="left">Product</th><th>YTD Sales</th><th>PYTD Sales</th><th>Variance</th></tr></thead><tbody><?php foreach($decl as $r):?><tr><td class="left"><?=md_h($r['customer'])?></td><td class="left prod"><?=md_h($r['product'])?></td><td><?=ld_money($r['ytd'])?></td><td><?=ld_money($r['pytd'])?></td><td class="neg"><?=ld_money($r['variance'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="section-card reports-card"><h3>Operational Reports</h3><div class="links"><a class="btn" href="inventory-dashboard.php">Inventory Action</a><a class="btn" href="inventory-risk.php">Inventory Risk</a><a class="btn" href="slow-inventory.php">Slow Inventory</a><a class="btn" href="open-orders.php">Open Sales Orders</a><a class="btn" href="open-po-dashboard.php">Open POs</a><a class="btn" href="supplier-scorecard.php">Supplier Scorecard</a><a class="btn" href="ytd-dashboard.php">YTD Dashboard</a></div></section>
<div class="foot">YTD metrics run through <?=md_d($latestInvoice)?>. Sales and profit are net of credits. Inventory aging and value are now based on the actual current Inventory lots rather than purchase-history estimates.</div><?php ld_foot(); ?>
