<?php
require_once __DIR__.'/inventory-model-v2.php';
function oo_h($v){return ld_h($v);} function oo_d($v){$t=strtotime((string)$v);return $t?date('M j, Y',$t):'-';}
try{$so=ld_rows('Open Sales Orders');}catch(Throwable $e){die(ld_h($e->getMessage()));}
$invMap=[];
foreach(($data['rows']??[]) as $r){
    $k=ld_key($r['product_code']??'');
    if($k==='')continue;
    $invMap[$k]=[
        'on_hand'=>(float)($r['on_hand_lbs']??0),
        'allocated'=>(float)($r['open_sales_orders_lbs']??0),
        'available'=>(float)($r['available_lbs']??0),
        'open_po'=>(float)($r['open_purchase_orders_lbs']??0),
    ];
}
$q=trim($_GET['q']??'');$rep=trim($_GET['rep']??'');$view=$_GET['view']??'all';$sort=$_GET['sort']??'ship';$reps=[];$rows=[];
foreach($so as $r){$repN=trim((string)($r['Rep Name']??''));if($repN!=='')$reps[$repN]=1;$cust=trim((string)($r['Customer Name']??''));$prod=trim((string)($r['Product Name']??''));$code=trim((string)($r['Product Number']??''));$ord=trim((string)($r['Order #']??''));if($q!==''&&!ld_contains($cust,$q)&&!ld_contains($prod,$q)&&!ld_contains($code,$q)&&!ld_contains($ord,$q))continue;if($rep!==''&&$repN!==$rep)continue;$k=ld_key($code);$stock=$invMap[$k]??['on_hand'=>0,'allocated'=>0,'available'=>0];$inbound=$stock['open_po']??0;$risk=$stock['available']<0; if($view==='risk'&&!$risk)continue;$rows[]=['order'=>$ord,'release'=>$r['Rel. No.']??'','customer'=>$cust,'date'=>$r['Order Date']??'','ship'=>$r['Ship Date']??'','product'=>$prod,'code'=>$code,'lbs'=>(float)($r['Total LBS']??0),'sales'=>(float)($r['Total $$']??0),'rep'=>$repN,'on_hand'=>$stock['on_hand'],'allocated'=>$stock['allocated'],'available'=>$stock['available'],'open_po'=>$inbound,'risk'=>$risk];}
ksort($reps,SORT_NATURAL|SORT_FLAG_CASE);usort($rows,function($a,$b)use($sort){if($sort==='lbs')return $b['lbs']<=>$a['lbs'];if($sort==='customer')return strcasecmp($a['customer'],$b['customer']);if($sort==='product')return strcasecmp($a['product'],$b['product']);return strcmp($a['ship'],$b['ship']);});
$sumLbs=array_sum(array_column($rows,'lbs'));$sumSales=array_sum(array_column($rows,'sales'));$riskProducts=[];foreach($rows as $r){if($r['risk'])$riskProducts[ld_key($r['code'])]=true;}$riskCount=count($riskProducts);$export=$rows;
ld_head('Open Sales Orders / Allocation','Customer commitments against current inventory and inbound supply');?>
<div class="cards"><div class="card"><div class="n"><?=ld_n(count($rows))?></div><div class="l">Open Order Lines</div></div><div class="card"><div class="n"><?=ld_n($sumLbs)?> lb</div><div class="l">Open Sales Order Pounds</div></div><div class="card"><div class="n"><?=ld_money($sumSales)?></div><div class="l">Open Sales Order Dollars</div></div><div class="card"><div class="n"><?=$riskCount?></div><div class="l">Products with Negative Available</div></div></div>
<section class="panel"><form class="filters"><div class="field wide"><label>Order / Customer / Product / Code</label><input name="q" value="<?=oo_h($q)?>"></div><div class="field"><label>Sales Rep</label><select name="rep"><option value="">All reps</option><?php foreach($reps as $r=>$x):?><option value="<?=oo_h($r)?>" <?=$rep===$r?'selected':''?>><?=oo_h($r)?></option><?php endforeach;?></select></div><div class="field"><label>View</label><select name="view"><option value="all" <?=$view==='all'?'selected':''?>>All orders</option><option value="risk" <?=$view==='risk'?'selected':''?>>Negative available only</option></select></div><div class="field"><label>Sort</label><select name="sort"><option value="ship" <?=$sort==='ship'?'selected':''?>>Ship date</option><option value="lbs" <?=$sort==='lbs'?'selected':''?>>Largest pounds</option><option value="customer" <?=$sort==='customer'?'selected':''?>>Customer</option><option value="product" <?=$sort==='product'?'selected':''?>>Product</option></select></div><button class="btn">Run</button><a class="btn alt" href="open-orders.php">Reset</a><button class="btn green" type="button" id="xlsxBtn">Download .xlsx</button></form></section>
<div class="tablewrap"><table><thead><tr><th class="left">Order #</th><th class="left">Release</th><th class="left">Customer</th><th class="left">Order Date</th><th class="left">Ship Date</th><th class="left prod">Product</th><th class="left">Product #</th><th>LBS</th><th>Sales $</th><th>On Hand LB</th><th>Allocated LB</th><th>Available LB</th><th>Open PO LB</th><th class="left">Rep</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td class="left"><?=oo_h($r['order'])?></td><td class="left"><?=oo_h($r['release'])?></td><td class="left"><?=oo_h($r['customer'])?></td><td class="left"><?=oo_d($r['date'])?></td><td class="left"><?=oo_d($r['ship'])?></td><td class="left prod"><?=oo_h($r['product'])?></td><td class="left"><?=oo_h($r['code'])?></td><td><?=ld_n($r['lbs'])?></td><td><?=ld_money($r['sales'])?></td><td><?=ld_n($r['on_hand'])?></td><td><?=ld_n($r['allocated'])?></td><td class="<?=$r['available']<0?'neg':''?>"><?=ld_n($r['available'])?></td><td><?=ld_n($r['open_po'])?></td><td class="left"><?=oo_h($r['rep'])?></td></tr><?php endforeach;?></tbody></table></div><div class="foot">Available inventory = current lot-level On Hand pounds - Open Sales Order pounds. Negative Available is highlighted as an exception; Open PO pounds are known inbound supply from the shared inventory model.</div>
<script src="https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js"></script><script>const rows=<?=json_encode($export,JSON_UNESCAPED_UNICODE)?>;document.getElementById('xlsxBtn').onclick=async()=>{if(!window.ExcelJS)return alert('Excel library could not load.');const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Open Sales Orders');const h=['Order #','Release','Customer','Order Date','Ship Date','Product','Product #','LBS','Sales $','On Hand LB','Allocated LB','Available LB','Open PO LB','Rep'];ws.addRow(h);rows.forEach(r=>ws.addRow([r.order,r.release,r.customer,r.date,r.ship,r.product,r.code,r.lbs,r.sales,r.on_hand,r.allocated,r.available,r.open_po,r.rep]));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF061D3F'}};ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:'N1'};[15,10,28,13,13,38,14,12,14,14,14,14,14,20].forEach((w,i)=>ws.getColumn(i+1).width=w);for(let r=2;r<=ws.rowCount;r++){[8,10,11,12,13].forEach(c=>ws.getCell(r,c).numFmt='#,##0;[Red](#,##0);-');ws.getCell(r,9).numFmt='$#,##0;[Red]($#,##0);-';}const b=await wb.xlsx.writeBuffer(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([b]));a.download='Lowe_Open_Sales_Orders_<?=date('Y-m-d')?>.xlsx';a.click();URL.revokeObjectURL(a.href);};</script><?php ld_foot(); ?>
