<?php
declare(strict_types=1);require_once __DIR__.'/inventory-model-v2.php';
function op_x($v){return ld_h($v);}function op_d($v){$d=of_date($v??'');return$d?date('M j, Y',strtotime($d)):'-';}
$map=[];foreach($data['rows'] as $r)$map[$r['product_code']]=$r;try{$po=ld_rows('Open Purchase Orders');}catch(Throwable $e){die(ld_h($e->getMessage()));}
$q=trim((string)($_GET['q']??''));$supplier=trim((string)($_GET['supplier']??''));$sups=[];$rows=[];$poTotals=[];
foreach($po as $r){$code=im_code($r['Product Number']??'');$sup=trim((string)($r['Supplier Name']??''));if($sup!=='')$sups[$sup]=true;$m=$map[$code]??[];$x=['po'=>$r['PO Number']??'','release'=>$r['Release Number']??'','date'=>of_date($r['PO Date']??''),'supplier'=>$sup,'code'=>$code,'product'=>trim((string)($r['Product Name']??($m['product_name']??''))),'lbs'=>of_num($r['LBS']??0),'costlb'=>of_num($r['Cost/LB']??0),'total'=>of_num($r['Total Cost']??0),'on_hand'=>$m['on_hand_lbs']??0,'open_so'=>$m['open_sales_orders_lbs']??0,'available'=>$m['available_lbs']??0,'all_open_po'=>$m['open_purchase_orders_lbs']??0,'projected'=>$m['projected_available_lbs']??0,'min_units'=>$m['min_units']??0,'max_units'=>$m['max_units']??0,'lead'=>$m['lead_time_days']??0];if($q!==''&&!ld_contains($x['product'],$q)&&!ld_contains($x['code'],$q)&&!ld_contains($x['po'],$q))continue;if($supplier!==''&&$sup!==$supplier)continue;$rows[]=$x;if($x['po']!=='')$poTotals[$x['po']]=true;}
ksort($sups,SORT_NATURAL|SORT_FLAG_CASE);$sumLbs=array_sum(array_column($rows,'lbs'));$sumCost=array_sum(array_column($rows,'total'));$pos=count(array_filter($rows,fn($r)=>$r['projected']>=0));$export=$rows;
ld_head('Open PO / Incoming Inventory','Open purchase orders against current lot-level inventory and customer commitments');?>
<div class="cards"><div class="card"><div class="n"><?=count($poTotals)?></div><div class="l">Open POs</div></div><div class="card"><div class="n"><?=ld_n($sumLbs)?> lb</div><div class="l">Inbound Pounds</div></div><div class="card"><div class="n"><?=ld_money($sumCost)?></div><div class="l">Open PO Value</div></div><div class="card"><div class="n"><?=$pos?></div><div class="l">Lines with Nonnegative Projected Available</div></div></div>
<section class="panel"><form class="filters"><div class="field wide"><label>PO / Product / Code</label><input name="q" value="<?=ld_h($q)?>"></div><div class="field"><label>Supplier</label><select name="supplier"><option value="">All suppliers</option><?php foreach(array_keys($sups) as $s):?><option value="<?=ld_h($s)?>" <?=$supplier===$s?'selected':''?>><?=ld_h($s)?></option><?php endforeach;?></select></div><button class="btn">Run</button><a class="btn alt" href="open-po-dashboard.php">Reset</a><button type="button" class="btn green" id="xlsxBtn">Download .xlsx</button></form></section>
<div class="tablewrap"><table><thead><tr><th class="left">PO #</th><th class="left">Release</th><th class="left">PO Date</th><th class="left">Supplier</th><th class="left">Product #</th><th class="left prod">Product</th><th>PO LBS</th><th>Cost/LB</th><th>Total Cost</th><th>On Hand</th><th>Open SO</th><th>Available</th><th>All Open PO</th><th>Projected Available</th><th>MIN</th><th>MAX</th><th>Lead Days</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td class="left"><?=op_x($r['po'])?></td><td class="left"><?=op_x($r['release'])?></td><td class="left"><?=op_d($r['date'])?></td><td class="left"><?=op_x($r['supplier'])?></td><td class="left"><?=op_x($r['code'])?></td><td class="left prod"><?=op_x($r['product'])?></td><td><?=ld_n($r['lbs'])?></td><td><?=ld_money($r['costlb'],4)?></td><td><?=ld_money($r['total'])?></td><td><?=ld_n($r['on_hand'])?></td><td><?=ld_n($r['open_so'])?></td><td class="<?=$r['available']<0?'neg':''?>"><?=ld_n($r['available'])?></td><td><?=ld_n($r['all_open_po'])?></td><td class="<?=$r['projected']<0?'neg':'pos'?>"><?=ld_n($r['projected'])?></td><td><?=$r['min_units']>0?ld_n($r['min_units']):'-'?></td><td><?=$r['max_units']>0?ld_n($r['max_units']):'-'?></td><td><?=$r['lead']>0?ld_n($r['lead']):'-'?></td></tr><?php endforeach;?></tbody></table></div><div class="foot">Projected Available = current Inventory Total LBs - all Open Sales Order LBs + all Open Purchase Order LBs for the SKU. MIN/MAX remain in workbook inventory units. The workbook still has no promised receipt date, so late/on-time status cannot be calculated.</div>
<script src="https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js"></script><script>const rows=<?=json_encode($export,JSON_UNESCAPED_UNICODE)?>;document.getElementById('xlsxBtn').onclick=async()=>{if(!window.ExcelJS)return alert('Excel library could not load.');const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Open PO');const h=['PO #','Release','PO Date','Supplier','Product #','Product','PO LBS','Cost/LB','Total Cost','On Hand','Open SO','Available','All Open PO','Projected Available','MIN','MAX','Lead Days'];ws.addRow(h);rows.forEach(r=>ws.addRow([r.po,r.release,r.date,r.supplier,r.code,r.product,r.lbs,r.costlb,r.total,r.on_hand,r.open_so,r.available,r.all_open_po,r.projected,r.min_units,r.max_units,r.lead]));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF061D3F'}};ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:'Q1'};const b=await wb.xlsx.writeBuffer(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([b]));a.download='Lowe_Open_PO_<?=date('Y-m-d')?>.xlsx';a.click();URL.revokeObjectURL(a.href);};</script><?php ld_foot(); ?>
