<?php
require_once __DIR__ . '/opportunity-config/app.php';
opp_require_device();
if (!opp_device()) { header('Location: opportunities.php'); exit; }
$pdo=opp_db();
$stages=['Lead','Qualified','Sample / Trial','Customer Testing','Quoting','Negotiation','Awaiting PO','On Hold'];
$data=[];$maxRevenue=0;
$stmt=$pdo->prepare("SELECT stage,COUNT(*) cnt,COALESCE(SUM(estimated_annual_revenue),0) revenue,COALESCE(SUM(weighted_pipeline_value),0) weighted FROM opportunities WHERE status IN ('Open','On Hold') GROUP BY stage");
$stmt->execute();
foreach($stmt->fetchAll() as $r){$data[$r['stage']]=$r;$maxRevenue=max($maxRevenue,(float)$r['revenue']);}
$cards=$pdo->query("SELECT id,opportunity_no,company_name,lowe_rep,stage,estimated_annual_revenue,probability,next_followup_date FROM opportunities WHERE status IN ('Open','On Hold') ORDER BY FIELD(stage,'Lead','Qualified','Sample / Trial','Customer Testing','Quoting','Negotiation','Awaiting PO','On Hold'), estimated_annual_revenue DESC")->fetchAll();
$byStage=[];foreach($cards as $c)$byStage[$c['stage']][]=$c;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Opportunity Funnel</title><style>
:root{--navy:#071f45;--blue:#163f78;--red:#d20f18;--line:#d6dbe6}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#eef2f7;color:#07152e}.page{max-width:1300px;margin:auto;padding:18px}.top{background:var(--blue);color:#fff;border-top:4px solid var(--red);border-radius:14px;padding:20px;display:flex;justify-content:space-between;align-items:center;gap:14px}.top h1{margin:0}.btn{display:inline-block;padding:9px 13px;border-radius:8px;text-decoration:none;font-weight:700;background:#fff;color:var(--navy)}.funnel{background:#fff;border:1px solid var(--line);border-radius:12px;padding:16px;margin-top:16px}.stage-line{display:grid;grid-template-columns:170px 1fr 240px;gap:12px;align-items:center;margin:10px 0}.stage-name{font-weight:800;color:var(--navy)}.barwrap{height:38px;background:#edf1f6;border-radius:8px;overflow:hidden}.bar{height:100%;background:#1f5b98;min-width:4px;display:flex;align-items:center;padding-left:10px;color:#fff;font-weight:700}.stats{text-align:right;font-size:14px}.board{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:16px}.col{background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden}.col h3{margin:0;background:var(--navy);color:#fff;padding:10px;font-size:15px}.opp{padding:10px;border-bottom:1px solid #e7ebf1}.opp:last-child{border-bottom:0}.opp a{color:var(--navy);font-weight:800;text-decoration:none}.muted{font-size:12px;color:#657288}.overdue{color:#b40000;font-weight:700}.empty{padding:10px;color:#657288;font-size:13px}@media(max-width:850px){.top{display:block;text-align:center}.top div:last-child{margin-top:12px}.stage-line{grid-template-columns:1fr}.stats{text-align:left}.board{grid-template-columns:1fr}.page{padding:10px}}
</style></head><body><main class="page"><div class="top"><div><h1>Opportunity Pipeline Funnel</h1><div>Stage progression, value and weighted pipeline.</div></div><div><a class="btn" href="salesworkflow.php">← Sales Workflow</a> <a class="btn" href="opportunities.php">Pipeline</a> <a class="btn" href="opportunity-tasks.php">Task Center</a> <a class="btn" href="opportunity-report.php">Reports</a></div></div>
<div class="funnel"><?php foreach($stages as $st): $r=$data[$st]??['cnt'=>0,'revenue'=>0,'weighted'=>0]; $pct=$maxRevenue>0?max(2,((float)$r['revenue']/$maxRevenue)*100):2; ?><div class="stage-line"><div class="stage-name"><?=opp_h($st)?></div><div class="barwrap"><div class="bar" style="width:<?=$pct?>%"><?=number_format((int)$r['cnt'])?> opp.</div></div><div class="stats"><?=opp_money($r['revenue'])?> &nbsp; | &nbsp; Weighted <?=opp_money($r['weighted'])?></div></div><?php endforeach;?></div>
<div class="board"><?php foreach($stages as $st):?><div class="col"><h3><?=opp_h($st)?></h3><?php if(empty($byStage[$st])):?><div class="empty">No opportunities</div><?php endif;?><?php foreach($byStage[$st]??[] as $o): $od=(!empty($o['next_followup_date'])&&$o['next_followup_date']<date('Y-m-d')); ?><div class="opp"><a href="opportunity.php?id=<?=(int)$o['id']?>"><?=opp_h($o['company_name'])?></a><div class="muted"><?=opp_h($o['opportunity_no'])?> • <?=opp_h($o['lowe_rep'])?></div><div><?=opp_money($o['estimated_annual_revenue'])?> • <?=number_format((float)$o['probability'],0)?>%</div><?php if($o['next_followup_date']):?><div class="muted <?=$od?'overdue':''?>">Follow-up: <?=opp_h($o['next_followup_date'])?><?=$od?' OVERDUE':''?></div><?php endif;?></div><?php endforeach;?></div><?php endforeach;?></div>
</main></body></html>