<?php
require __DIR__ . '/opportunity-config/app.php';
opp_require_device();
$pdo=opp_db();
$year=max(2020,min(2100,(int)($_GET['year']??date('Y'))));
$rep=trim($_GET['rep']??'');
$reps=$pdo->query("SELECT DISTINCT lowe_rep FROM opportunities WHERE lowe_rep IS NOT NULL AND lowe_rep<>'' ORDER BY lowe_rep")->fetchAll(PDO::FETCH_COLUMN);
$repWhere=$rep!==''?' AND o.lowe_rep=?':'';$rp=$rep!==''?[$rep]:[];
$stmt=$pdo->prepare("SELECT COUNT(*) open_count,COALESCE(SUM(estimated_annual_revenue),0) pipeline,COALESCE(SUM(weighted_pipeline_value),0) weighted,COALESCE(SUM(estimated_annual_gp),0) expected_gp,SUM(next_followup_date<CURDATE()) overdue_followups,SUM(expected_close_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY)) closing30 FROM opportunities o WHERE status='Open'".$repWhere);$stmt->execute($rp);$open=$stmt->fetch(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare("SELECT SUM(status='Won') won_count,SUM(status='Lost') lost_count,COALESCE(SUM(CASE WHEN status='Won' THEN actual_annual_revenue ELSE 0 END),0) won_revenue,COALESCE(SUM(CASE WHEN status='Won' THEN actual_annual_gp ELSE 0 END),0) won_gp FROM opportunities o WHERE status IN ('Won','Lost') AND YEAR(COALESCE(won_date,lost_date,closed_at))=?".$repWhere);$stmt->execute(array_merge([$year],$rp));$closed=$stmt->fetch(PDO::FETCH_ASSOC);$decisions=(int)$closed['won_count']+(int)$closed['lost_count'];$winRate=$decisions?((int)$closed['won_count']/$decisions*100):0;
$stmt=$pdo->prepare("SELECT COUNT(*) c FROM opportunity_tasks t JOIN opportunities o ON o.id=t.opportunity_id WHERE t.completed=0 AND t.due_date<CURDATE() AND o.status='Open'".$repWhere);$stmt->execute($rp);$overdueTasks=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT COUNT(*) c,COALESCE(SUM(q.quote_amount),0) amount FROM opportunity_quotes q JOIN opportunities o ON o.id=q.opportunity_id WHERE q.quote_status IN ('Sent','Revised') AND o.status='Open'".$repWhere);$stmt->execute($rp);$quotesWaiting=$stmt->fetch(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare("SELECT o.lowe_rep,COUNT(*) open_count,COALESCE(SUM(o.estimated_annual_revenue),0) pipeline,COALESCE(SUM(o.weighted_pipeline_value),0) weighted,COALESCE(SUM(o.estimated_annual_gp),0) gp,SUM(o.next_followup_date<CURDATE()) overdue FROM opportunities o WHERE o.status='Open' GROUP BY o.lowe_rep ORDER BY weighted DESC");$stmt->execute();$repOpen=[];foreach($stmt as $r)$repOpen[$r['lowe_rep']?:'Unassigned']=$r;
$stmt=$pdo->prepare("SELECT o.lowe_rep,SUM(o.status='Won') won,SUM(o.status='Lost') lost,COALESCE(SUM(CASE WHEN o.status='Won' THEN o.actual_annual_revenue ELSE 0 END),0) won_revenue,COALESCE(SUM(CASE WHEN o.status='Won' THEN o.actual_annual_gp ELSE 0 END),0) won_gp FROM opportunities o WHERE o.status IN ('Won','Lost') AND YEAR(COALESCE(o.won_date,o.lost_date,o.closed_at))=? GROUP BY o.lowe_rep");$stmt->execute([$year]);$repClosed=[];foreach($stmt as $r)$repClosed[$r['lowe_rep']?:'Unassigned']=$r;
$repNames=array_unique(array_merge(array_keys($repOpen),array_keys($repClosed)));sort($repNames);
$stmt=$pdo->prepare("SELECT stage,COUNT(*) cnt,COALESCE(SUM(estimated_annual_revenue),0) revenue,COALESCE(SUM(weighted_pipeline_value),0) weighted FROM opportunities o WHERE status='Open'".$repWhere." GROUP BY stage ORDER BY weighted DESC");$stmt->execute($rp);$stages=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare("SELECT COALESCE(NULLIF(p.supplier,''),'Unspecified') supplier,COUNT(DISTINCT o.id) opportunities,COALESCE(SUM(p.annual_volume),0) volume,COALESCE(SUM(p.est_annual_revenue),0) revenue,COALESCE(SUM(p.est_annual_gp),0) gp FROM opportunity_products p JOIN opportunities o ON o.id=p.opportunity_id WHERE o.status='Open'".$repWhere." GROUP BY supplier ORDER BY revenue DESC LIMIT 12");$stmt->execute($rp);$suppliers=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare("SELECT q.quote_status,COUNT(*) cnt,COALESCE(SUM(q.quote_amount),0) amount FROM opportunity_quotes q JOIN opportunities o ON o.id=q.opportunity_id WHERE YEAR(q.quote_date)=?".$repWhere." GROUP BY q.quote_status ORDER BY cnt DESC");$stmt->execute(array_merge([$year],$rp));$quoteStats=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stmt=$pdo->prepare("SELECT COALESCE(NULLIF(o.lost_reason,''),'Unspecified') reason,COUNT(*) cnt FROM opportunities o WHERE o.status='Lost' AND YEAR(COALESCE(o.lost_date,o.closed_at))=?".$repWhere." GROUP BY reason ORDER BY cnt DESC");$stmt->execute(array_merge([$year],$rp));$loss=$stmt->fetchAll(PDO::FETCH_ASSOC);
function pct($a,$b){return $b?number_format($a/$b*100,1).'%':'0.0%';}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Management Dashboard - Lowe Chemical</title><style>
:root{--navy:#071f45;--blue:#163f78;--red:#d20f18;--line:#d6dbe6;--green:#27864b}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#eef2f7;color:#07152e}.page{max-width:1450px;margin:auto;padding:18px}.top{background:var(--blue);color:#fff;border-top:4px solid var(--red);padding:20px 24px;border-radius:14px;display:flex;justify-content:space-between;gap:12px;align-items:center}.top h1{margin:0}.btn{display:inline-block;padding:9px 13px;border-radius:8px;text-decoration:none;font-weight:700;border:0;cursor:pointer}.white{background:#fff;color:var(--navy)}.navy{background:#1f5b98;color:#fff}.filters{margin:14px 0;background:#fff;border:1px solid var(--line);border-radius:12px;padding:12px;display:flex;gap:10px;align-items:end}.filters label{display:block;font-size:11px;font-weight:700;color:#68758a;text-transform:uppercase}.filters select{padding:9px;border:1px solid #cbd2df;border-radius:7px;min-width:180px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric,.card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:15px}.metric .label{font-size:11px;color:#68758a;text-transform:uppercase}.metric .value{font-size:25px;font-weight:800;color:var(--navy);margin-top:5px}.metric .sub{font-size:12px;color:#68758a;margin-top:4px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.card h2{font-size:17px;color:var(--navy);margin:0 0 12px}table{width:100%;border-collapse:collapse}th{background:#0f3769;color:#fff;padding:9px;text-align:left;font-size:12px}td{padding:9px;border-bottom:1px solid #e7ebf1;font-size:13px}.money{text-align:right}.bar{height:8px;background:#e7ecf3;border-radius:10px;overflow:hidden}.bar span{height:100%;display:block;background:#1f5b98}.good{color:#18723a;font-weight:700}.bad{color:#a12525;font-weight:700}.muted{color:#68758a;font-size:12px}@media(max-width:900px){.metrics{grid-template-columns:1fr 1fr}.grid2{grid-template-columns:1fr}.top{display:block}.top div:last-child{margin-top:10px}.filters{display:block}.filters>*{margin-top:8px}.filters select,.filters .btn{width:100%}.tablewrap{overflow-x:auto}}@media(max-width:520px){.metrics{grid-template-columns:1fr}}
</style></head><body><main class="page"><div class="top"><div><h1>Management Dashboard</h1><div>Lowe Chemical Opportunity Pipeline performance and sales forecast.</div></div><div><a class="btn white" href="salesworkflow.php">← Sales Workflow</a> <a class="btn white" href="opportunities.php">Pipeline</a> <a class="btn white" href="opportunity-tasks.php">Task Center</a> <a class="btn white" href="opportunity-report.php">Reports</a> <a class="btn white" href="opportunity-funnel.php">Funnel</a> <a class="btn white" href="opportunity-closed.php">Closed</a></div></div>
<form class="filters"><div><label>Reporting Year</label><select name="year"><?php for($y=(int)date('Y');$y>=2025;$y--):?><option <?=$year===$y?'selected':''?>><?=$y?></option><?php endfor;?></select></div><div><label>Sales Rep</label><select name="rep"><option value="">All Sales Reps</option><?php foreach($reps as $r):?><option value="<?=opp_h($r)?>" <?=$rep===$r?'selected':''?>><?=opp_h($r)?></option><?php endforeach;?></select></div><button class="btn navy">Apply</button></form>
<div class="metrics"><div class="metric"><div class="label">Open Opportunities</div><div class="value"><?=number_format((int)$open['open_count'])?></div><div class="sub"><?=opp_money($open['pipeline'])?> pipeline</div></div><div class="metric"><div class="label">Weighted Pipeline</div><div class="value"><?=opp_money($open['weighted'])?></div><div class="sub"><?=opp_money($open['expected_gp'])?> expected GP</div></div><div class="metric"><div class="label">Won Revenue <?=$year?></div><div class="value"><?=opp_money($closed['won_revenue'])?></div><div class="sub"><?=opp_money($closed['won_gp'])?> actual GP</div></div><div class="metric"><div class="label">Win Rate <?=$year?></div><div class="value"><?=number_format($winRate,1)?>%</div><div class="sub"><?=number_format((int)$closed['won_count'])?> won / <?=number_format($decisions)?> decisions</div></div><div class="metric"><div class="label">Overdue Follow-Ups</div><div class="value"><?=number_format((int)$open['overdue_followups'])?></div><div class="sub">Open opportunities</div></div><div class="metric"><div class="label">Overdue Tasks</div><div class="value"><?=number_format($overdueTasks)?></div><div class="sub">Needs sales attention</div></div><div class="metric"><div class="label">Quotes Awaiting Decision</div><div class="value"><?=number_format((int)$quotesWaiting['c'])?></div><div class="sub"><?=opp_money($quotesWaiting['amount'])?> quoted</div></div><div class="metric"><div class="label">Closing Next 30 Days</div><div class="value"><?=number_format((int)$open['closing30'])?></div><div class="sub">Expected close dates</div></div></div>
<div class="grid2"><section class="card tablewrap"><h2>Sales Rep Scorecard</h2><table><thead><tr><th>Rep</th><th>Open</th><th class="money">Pipeline</th><th class="money">Weighted</th><th>Won</th><th>Lost</th><th>Win Rate</th><th class="money">Won Revenue</th><th class="money">Won GP</th><th>Overdue</th></tr></thead><tbody><?php foreach($repNames as $name):$a=$repOpen[$name]??[];$b=$repClosed[$name]??[];$w=(int)($b['won']??0);$l=(int)($b['lost']??0);?><tr><td><strong><?=opp_h($name)?></strong></td><td><?=number_format((int)($a['open_count']??0))?></td><td class="money"><?=opp_money($a['pipeline']??0)?></td><td class="money"><?=opp_money($a['weighted']??0)?></td><td class="good"><?=$w?></td><td class="bad"><?=$l?></td><td><?=pct($w,$w+$l)?></td><td class="money"><?=opp_money($b['won_revenue']??0)?></td><td class="money"><?=opp_money($b['won_gp']??0)?></td><td><?=number_format((int)($a['overdue']??0))?></td></tr><?php endforeach;?></tbody></table></section>
<section class="card"><h2>Open Pipeline by Stage</h2><?php $mx=max(array_map(fn($r)=>(float)$r['revenue'],$stages)?:[1]);foreach($stages as $s):?><div style="margin:11px 0"><div style="display:flex;justify-content:space-between;gap:8px"><strong><?=opp_h($s['stage'])?></strong><span><?=number_format((int)$s['cnt'])?> · <?=opp_money($s['revenue'])?> · weighted <?=opp_money($s['weighted'])?></span></div><div class="bar"><span style="width:<?=min(100,$mx?($s['revenue']/$mx*100):0)?>%"></span></div></div><?php endforeach;?><?php if(!$stages):?><div class="muted">No open pipeline.</div><?php endif;?></section></div>
<div class="grid2"><section class="card tablewrap"><h2>Open Product / Supplier Pipeline</h2><table><thead><tr><th>Supplier</th><th>Opps</th><th class="money">Annual Volume*</th><th class="money">Revenue</th><th class="money">GP</th></tr></thead><tbody><?php foreach($suppliers as $s):?><tr><td><?=opp_h($s['supplier'])?></td><td><?=number_format((int)$s['opportunities'])?></td><td class="money"><?=number_format((float)$s['volume'],0)?></td><td class="money"><?=opp_money($s['revenue'])?></td><td class="money"><?=opp_money($s['gp'])?></td></tr><?php endforeach;?></tbody></table><div class="muted" style="margin-top:8px">*Volume totals are shown numerically. Review units before combining products with different volume units.</div></section>
<section class="card tablewrap"><h2>Quote Conversion <?=$year?></h2><table><thead><tr><th>Status</th><th>Quotes</th><th class="money">Amount</th></tr></thead><tbody><?php foreach($quoteStats as $q):?><tr><td><?=opp_h($q['quote_status'])?></td><td><?=number_format((int)$q['cnt'])?></td><td class="money"><?=opp_money($q['amount'])?></td></tr><?php endforeach;?><?php if(!$quoteStats):?><tr><td colspan="3">No quotes for this period.</td></tr><?php endif;?></tbody></table><h2 style="margin-top:20px">Lost Business Reasons <?=$year?></h2><table><thead><tr><th>Reason</th><th>Count</th></tr></thead><tbody><?php foreach($loss as $l):?><tr><td><?=opp_h($l['reason'])?></td><td><?=number_format((int)$l['cnt'])?></td></tr><?php endforeach;?><?php if(!$loss):?><tr><td colspan="2">No lost opportunities for this period.</td></tr><?php endif;?></tbody></table></section></div>
</main></body></html>
