<?php
require_once __DIR__ . '/opportunity-config/app.php';
opp_require_device();

if (!opp_device()) {
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lowe Opportunity Pipeline</title><style>body{font-family:Arial;background:#eef2f7;margin:0}.card{max-width:700px;margin:8vh auto;background:#fff;padding:34px;border-radius:16px;box-shadow:0 12px 34px rgba(0,0,0,.12);text-align:center}.logo{width:280px;max-width:80%}h1{color:#071f45}.choices{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:28px}button{padding:22px;border:0;border-radius:12px;font-size:20px;font-weight:700;cursor:pointer}.desktop{background:#071f45;color:#fff}.mobile{background:#d20f18;color:#fff}@media(max-width:650px){.choices{grid-template-columns:1fr}}</style></head><body><div class="card"><img class="logo" src="images/lowelogo1.png"><h1>Opportunity Pipeline</h1><p>How are you using the Opportunity Pipeline?</p><form method="post"><div class="choices"><button class="desktop" name="device_choice" value="desktop">Desktop / Laptop</button><button class="mobile" name="device_choice" value="mobile">Mobile Phone</button></div></form><div style="margin-top:18px"><a href="salesworkflow.php" style="display:inline-block;padding:10px 14px;border-radius:8px;background:#e8edf5;color:#071f45;text-decoration:none;font-weight:700">← Sales Workflow</a></div></div></body></html><?php exit; }

$device = opp_device();
$q = trim($_GET['q'] ?? '');
$stage = trim($_GET['stage'] ?? '');
$rep = trim($_GET['rep'] ?? '');
$view = trim($_GET['view'] ?? 'open');
if (!in_array($view,['open','closed','all'],true)) $view='open';
$where=[];$params=[];
if($view==='open') $where[]="status IN ('Open','On Hold')";
elseif($view==='closed') $where[]="status IN ('Won','Lost')";
if($q!==''){ $where[]='(company_name LIKE ? OR opportunity_no LIKE ? OR primary_contact LIKE ? OR industry_application LIKE ?)'; for($i=0;$i<4;$i++)$params[]='%'.$q.'%'; }
if($stage!==''){ $where[]='stage=?'; $params[]=$stage; }
if($rep!==''){ $where[]='lowe_rep=?'; $params[]=$rep; }
$sql='SELECT * FROM opportunities'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY updated_at DESC';
$stmt=opp_db()->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();
$summary=opp_db()->query("SELECT SUM(CASE WHEN status='Open' THEN 1 ELSE 0 END) open_count, COALESCE(SUM(CASE WHEN status='Open' THEN estimated_annual_revenue ELSE 0 END),0) pipeline, COALESCE(SUM(CASE WHEN status='Open' THEN weighted_pipeline_value ELSE 0 END),0) weighted, COALESCE(SUM(CASE WHEN status='Open' THEN estimated_annual_gp ELSE 0 END),0) gp, SUM(CASE WHEN status='Open' AND next_followup_date<CURDATE() THEN 1 ELSE 0 END) overdue, SUM(CASE WHEN status='Open' AND expected_close_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY) THEN 1 ELSE 0 END) closing_30 FROM opportunities")->fetch();
$taskSummary=opp_db()->query("SELECT SUM(CASE WHEN completed=0 THEN 1 ELSE 0 END) open_tasks, SUM(CASE WHEN completed=0 AND due_date<CURDATE() THEN 1 ELSE 0 END) overdue_tasks FROM opportunity_tasks")->fetch();
$reps=opp_db()->query("SELECT DISTINCT lowe_rep FROM opportunities WHERE lowe_rep IS NOT NULL AND lowe_rep<>'' ORDER BY lowe_rep")->fetchAll(PDO::FETCH_COLUMN);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lowe Opportunity Pipeline</title><style>
:root{--navy:#071f45;--red:#d20f18;--line:#d6dbe6;--light:#f5f7fb;--text:#07152e}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#eef2f7;color:var(--text)}.page{max-width:1400px;margin:auto;padding:18px}.top{background:#163f78;color:#fff;border-top:4px solid var(--red);padding:20px 26px;border-radius:14px;display:flex;justify-content:space-between;align-items:center;gap:16px}.top h1{margin:0}.btn{display:inline-block;padding:10px 14px;border-radius:8px;text-decoration:none;font-weight:700;border:0;cursor:pointer}.white{background:#fff;color:#071f45}.red{background:#b73535;color:#fff}.navy{background:#1c5b97;color:#fff}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metric{background:#fff;border:1px solid var(--line);border-radius:12px;padding:16px}.metric .label{font-size:12px;color:#68758a;text-transform:uppercase}.metric .value{font-size:26px;font-weight:800;color:var(--navy);margin-top:5px}.filters{background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px;display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:10px;margin-bottom:14px}.filters input,.filters select{width:100%;padding:10px;border:1px solid #cbd2df;border-radius:8px}.tablewrap{background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden}table{width:100%;border-collapse:collapse}th{background:#0f3769;color:#fff;padding:11px;text-align:left;font-size:13px}td{padding:11px;border-bottom:1px solid #e7ebf1;font-size:14px}.money{text-align:right}.stage{font-weight:700}.mobile-card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:15px;margin-bottom:12px}.mobile-card h3{margin:0 0 6px;color:var(--navy)}.mobile-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:14px}.muted{color:#68758a;font-size:12px}.overdue-row{background:#fff1f1!important}.overdue-card{border:2px solid #d20f18!important}.overdue-tag{display:inline-block;background:#d20f18;color:#fff;font-size:11px;font-weight:700;padding:3px 6px;border-radius:5px;margin-top:4px}
<?php if($device==='mobile'): ?>.page{padding:10px}.top{display:block;text-align:center}.top .actions{margin-top:12px}.cards{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr}.desktop-only{display:none!important}.metric .value{font-size:21px}.mobile-grid{grid-template-columns:1fr}<?php else: ?>.mobile-only{display:none!important}@media(max-width:900px){.cards{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr 1fr}.tablewrap{overflow-x:auto}}<?php endif; ?>
</style></head><body><main class="page"><div class="top"><div><h1>Lowe Chemical Opportunity Pipeline</h1><div>Track customer opportunities, value, stage, follow-up and close timing.</div></div><div class="actions"><a class="btn white" href="salesworkflow.php">← Sales Workflow</a> <a class="btn white" href="opportunity-new.php">+ New Opportunity</a> <a class="btn white" href="opportunity-tasks.php">Task Center</a> <a class="btn white" href="opportunity-dashboard.php">Management Dashboard</a> <a class="btn white" href="opportunity-report.php">Reports</a> <a class="btn white" href="opportunity-funnel.php">Funnel</a> <a class="btn white" href="opportunity-closed.php">Closed</a> <a class="btn navy" href="?change_device=1">Change Device</a></div></div>
<div style="margin:14px 0;display:flex;gap:8px;flex-wrap:wrap"><a class="btn <?= $view==='open'?'navy':'white' ?>" href="opportunities.php?view=open">Open</a><a class="btn <?= $view==='closed'?'navy':'white' ?>" href="opportunities.php?view=closed">Closed</a><a class="btn <?= $view==='all'?'navy':'white' ?>" href="opportunities.php?view=all">All</a></div>
<div class="cards"><div class="metric"><div class="label">Open Opportunities</div><div class="value"><?=number_format((int)$summary['open_count'])?></div></div><div class="metric"><div class="label">Pipeline $</div><div class="value"><?=opp_money($summary['pipeline'])?></div></div><div class="metric"><div class="label">Weighted Pipeline</div><div class="value"><?=opp_money($summary['weighted'])?></div></div><div class="metric"><div class="label">Expected GP</div><div class="value"><?=opp_money($summary['gp'])?></div></div><div class="metric"><div class="label">Closing Next 30 Days</div><div class="value"><?=number_format((int)$summary['closing_30'])?></div></div><div class="metric"><div class="label">Overdue Follow-Ups</div><div class="value"><?=number_format((int)$summary['overdue'])?></div></div><div class="metric"><div class="label">Open Tasks</div><div class="value"><?=number_format((int)$taskSummary['open_tasks'])?></div></div><div class="metric"><div class="label">Overdue Tasks</div><div class="value"><?=number_format((int)$taskSummary['overdue_tasks'])?></div></div></div>
<form class="filters"><input type="hidden" name="view" value="<?=opp_h($view)?>"><input name="q" value="<?=opp_h($q)?>" placeholder="Search company, opportunity #, contact or application"><select name="stage"><option value="">All stages</option><?php foreach(opp_stages() as $s):?><option value="<?=opp_h($s)?>" <?=$stage===$s?'selected':''?>><?=opp_h($s)?></option><?php endforeach;?></select><select name="rep"><option value="">All reps</option><?php foreach($reps as $r):?><option value="<?=opp_h($r)?>" <?=$rep===$r?'selected':''?>><?=opp_h($r)?></option><?php endforeach;?></select><button class="btn navy">Search</button></form>
<div class="tablewrap desktop-only"><table><thead><tr><th>Opportunity #</th><th>Customer</th><th>Rep</th><th>Stage</th><th>Annual Revenue</th><th>Probability</th><th>Expected Close</th><th>Next Action</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9">No opportunities yet.</td></tr><?php endif;?><?php foreach($rows as $r): $isOverdue=($r['status']==='Open' && !empty($r['next_followup_date']) && $r['next_followup_date'] < date('Y-m-d')); ?><tr class="<?=$isOverdue?'overdue-row':''?>"><td><strong><?=opp_h($r['opportunity_no'])?></strong></td><td><?=opp_h($r['company_name'])?><div class="muted"><?=opp_h($r['primary_contact'])?></div></td><td><?=opp_h($r['lowe_rep'])?></td><td class="stage"><?=opp_h($r['stage'])?></td><td class="money"><?=opp_money($r['estimated_annual_revenue'])?></td><td><?=number_format((float)$r['probability'],0)?>%</td><td><?=opp_h($r['expected_close_date'])?></td><td><?=opp_h($r['next_action'])?><div class="muted"><?=opp_h($r['next_followup_date'])?></div><?php if($isOverdue):?><span class="overdue-tag">FOLLOW-UP OVERDUE</span><?php endif;?></td><td><a class="btn navy" href="opportunity.php?id=<?=(int)$r['id']?>">Open</a></td></tr><?php endforeach;?></tbody></table></div>
<div class="mobile-only"><?php if(!$rows):?><div class="mobile-card">No opportunities yet.</div><?php endif;?><?php foreach($rows as $r): $isOverdue=($r['status']==='Open' && !empty($r['next_followup_date']) && $r['next_followup_date'] < date('Y-m-d')); ?><div class="mobile-card <?=$isOverdue?'overdue-card':''?>"><h3><?=opp_h($r['company_name'])?></h3><div class="muted"><?=opp_h($r['opportunity_no'])?></div><div class="mobile-grid"><div><strong>Stage:</strong> <?=opp_h($r['stage'])?></div><div><strong>Rep:</strong> <?=opp_h($r['lowe_rep'])?></div><div><strong>Annual:</strong> <?=opp_money($r['estimated_annual_revenue'])?></div><div><strong>Probability:</strong> <?=number_format((float)$r['probability'],0)?>%</div><div><strong>Expected Close:</strong> <?=opp_h($r['expected_close_date'])?></div><div><strong>Next Follow-Up:</strong> <?=opp_h($r['next_followup_date'])?><?php if($isOverdue):?> <span class="overdue-tag">OVERDUE</span><?php endif;?></div></div><div style="margin-top:12px"><a class="btn navy" href="opportunity.php?id=<?=(int)$r['id']?>">Open Opportunity</a></div></div><?php endforeach;?></div>
</main></body></html>
