<?php
require_once __DIR__ . '/opportunity-config/app.php';
require_once __DIR__ . '/includes/workflow-nav.php';
opp_require_device();
if (!opp_device()) { header('Location: opportunities.php'); exit; }
$pdo=opp_db();
$stageRows=$pdo->query("SELECT stage,COUNT(*) opp_count,COALESCE(SUM(estimated_annual_revenue),0) revenue,COALESCE(SUM(weighted_pipeline_value),0) weighted,COALESCE(SUM(estimated_annual_gp),0) gp FROM opportunities WHERE status='Open' GROUP BY stage ORDER BY revenue DESC")->fetchAll();
$repRows=$pdo->query("SELECT COALESCE(NULLIF(lowe_rep,''),'Unassigned') rep,COUNT(*) opp_count,COALESCE(SUM(estimated_annual_revenue),0) revenue,COALESCE(SUM(weighted_pipeline_value),0) weighted,COALESCE(SUM(estimated_annual_gp),0) gp FROM opportunities WHERE status='Open' GROUP BY rep ORDER BY revenue DESC")->fetchAll();
$supplierRows=$pdo->query("SELECT COALESCE(NULLIF(p.supplier,''),'Unspecified') supplier,
    COUNT(DISTINCT p.opportunity_id) opp_count,
    COUNT(*) product_lines,
    COALESCE(SUM(p.est_annual_revenue),0) revenue,
    COALESCE(SUM(CASE WHEN p.est_cost > 0 THEN p.est_annual_gp ELSE 0 END),0) gp,
    SUM(CASE WHEN p.est_annual_revenue > 0 THEN 1 ELSE 0 END) priced_lines,
    SUM(CASE WHEN p.est_annual_revenue > 0 AND p.est_cost > 0 THEN 1 ELSE 0 END) cost_known_lines
    FROM opportunity_products p
    JOIN opportunities o ON o.id=p.opportunity_id
    WHERE o.status='Open'
    GROUP BY supplier ORDER BY revenue DESC LIMIT 25")->fetchAll();
$closeRows=$pdo->query("SELECT opportunity_no,company_name,lowe_rep,stage,expected_close_date,estimated_annual_revenue,probability FROM opportunities WHERE status='Open' AND expected_close_date IS NOT NULL ORDER BY expected_close_date ASC LIMIT 30")->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lowe Pipeline Reports</title><style>
:root{--navy:#071f45;--blue:#163f78;--red:#d20f18;--line:#d6dbe6}*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#eef2f7;color:#07152e}.page{max-width:1250px;margin:auto;padding:18px}.top{background:var(--blue);color:#fff;border-top:4px solid var(--red);padding:20px 24px;border-radius:14px;display:flex;justify-content:space-between;align-items:center}.top h1{margin:0}.btn{display:inline-block;padding:9px 13px;border-radius:8px;text-decoration:none;font-weight:700}.white{background:#fff;color:var(--navy)}.card{background:#fff;border:1px solid var(--line);border-radius:12px;margin-top:14px;overflow:hidden}.title{background:var(--navy);color:#fff;padding:10px 14px;font-weight:700}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #e7ebf1;text-align:left}th{background:#f1f4f8}.money{text-align:right}.muted{color:#66758b;font-size:12px}@media(max-width:760px){.page{padding:10px}.top{display:block;text-align:center}.top div:last-child{margin-top:10px}.card{overflow-x:auto}table{min-width:680px}}
</style></head><body><main class="page"><div class="top"><div><h1>Opportunity Pipeline Reports</h1><div>Stage, rep, supplier and close-date views.</div></div><div><?=workflow_back_link('btn white')?> <a class="btn white" href="opportunities.php">Pipeline</a> <a class="btn white" href="opportunity-tasks.php">Task Center</a></div></div>
<div class="card"><div class="title">Pipeline by Stage</div><table><thead><tr><th>Stage</th><th>Opportunities</th><th class="money">Annual Revenue</th><th class="money">Weighted Pipeline</th><th class="money">Expected GP</th></tr></thead><tbody><?php foreach($stageRows as $r): ?><tr><td><strong><?=opp_h($r['stage'])?></strong></td><td><?=number_format((int)$r['opp_count'])?></td><td class="money"><?=opp_money($r['revenue'])?></td><td class="money"><?=opp_money($r['weighted'])?></td><td class="money"><?=opp_money($r['gp'])?></td></tr><?php endforeach; ?><?php if(!$stageRows): ?><tr><td colspan="5">No open opportunities.</td></tr><?php endif; ?></tbody></table></div>
<div class="card"><div class="title">Pipeline by Sales Rep</div><table><thead><tr><th>Sales Rep</th><th>Opportunities</th><th class="money">Annual Revenue</th><th class="money">Weighted Pipeline</th><th class="money">Expected GP</th></tr></thead><tbody><?php foreach($repRows as $r): ?><tr><td><strong><?=opp_h($r['rep'])?></strong></td><td><?=number_format((int)$r['opp_count'])?></td><td class="money"><?=opp_money($r['revenue'])?></td><td class="money"><?=opp_money($r['weighted'])?></td><td class="money"><?=opp_money($r['gp'])?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="card"><div class="title">Open Opportunity Products by Supplier</div><table><thead><tr><th>Supplier</th><th>Opportunities</th><th>Product Lines</th><th class="money">Est. Product Revenue</th><th class="money">Est. Product GP</th></tr></thead><tbody><?php foreach($supplierRows as $r): ?><tr><td><strong><?=opp_h($r['supplier'])?></strong></td><td><?=number_format((int)$r['opp_count'])?></td><td><?=number_format((int)$r['product_lines'])?></td><td class="money"><?=opp_money($r['revenue'])?></td><td class="money"><?php if((int)$r['priced_lines'] > (int)$r['cost_known_lines']): ?><span class="muted">Cost not entered</span><?php else: ?><?=opp_money($r['gp'])?><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$supplierRows): ?><tr><td colspan="5">No supplier data entered yet.</td></tr><?php endif; ?></tbody></table></div>
<div class="card"><div class="title">Upcoming Expected Close Dates</div><table><thead><tr><th>Expected Close</th><th>Customer</th><th>Opportunity</th><th>Rep</th><th>Stage</th><th>Probability</th><th class="money">Annual Revenue</th></tr></thead><tbody><?php foreach($closeRows as $r): ?><tr><td><?=opp_h($r['expected_close_date'])?></td><td><?=opp_h($r['company_name'])?></td><td><?=opp_h($r['opportunity_no'])?></td><td><?=opp_h($r['lowe_rep'])?></td><td><?=opp_h($r['stage'])?></td><td><?=number_format((float)$r['probability'],0)?>%</td><td class="money"><?=opp_money($r['estimated_annual_revenue'])?></td></tr><?php endforeach; ?><?php if(!$closeRows): ?><tr><td colspan="7">No expected close dates entered.</td></tr><?php endif; ?></tbody></table></div>
</main></body></html>
