<?php
require_once __DIR__ . '/opportunity-config/app.php';
require_once __DIR__ . '/includes/workflow-nav.php';
opp_require_device();
if (!opp_device()) { header('Location: opportunities.php'); exit; }
$pdo=opp_db();
$rep=trim($_GET['rep'] ?? '');
$params=[];
$where="status IN ('Won','Lost')";
if($rep!==''){ $where.=' AND lowe_rep=?'; $params[]=$rep; }
$stmt=$pdo->prepare("SELECT * FROM opportunities WHERE $where ORDER BY COALESCE(closed_at,updated_at) DESC");$stmt->execute($params);$rows=$stmt->fetchAll();
$sumSql="SELECT SUM(status='Won') won_count,SUM(status='Lost') lost_count,COALESCE(SUM(CASE WHEN status='Won' THEN actual_annual_revenue ELSE 0 END),0) won_revenue,COALESCE(SUM(CASE WHEN status='Won' THEN actual_annual_gp ELSE 0 END),0) won_gp FROM opportunities WHERE $where";
$s=$pdo->prepare($sumSql);$s->execute($params);$summary=$s->fetch();
$closedCount=(int)$summary['won_count']+(int)$summary['lost_count'];$winRate=$closedCount?((int)$summary['won_count']/$closedCount)*100:0;
$reasons=$pdo->prepare("SELECT COALESCE(NULLIF(lost_reason,''),'Unspecified') reason,COUNT(*) cnt FROM opportunities WHERE status='Lost'".($rep!==''?' AND lowe_rep=?':'')." GROUP BY reason ORDER BY cnt DESC,reason");$reasons->execute($rep!==''?[$rep]:[]);$lossReasons=$reasons->fetchAll();
$reps=$pdo->query("SELECT DISTINCT lowe_rep FROM opportunities WHERE lowe_rep IS NOT NULL AND lowe_rep<>'' ORDER BY lowe_rep")->fetchAll(PDO::FETCH_COLUMN);
$device=opp_device();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Closed Opportunities - Lowe Chemical</title><style>
:root{--navy:#071f45;--blue:#163f78;--red:#d20f18;--line:#d6dbe6;--green:#27864b}*{box-sizing:border-box}body{margin:0;font-family:Arial;background:#eef2f7;color:#07152e}.page{max-width:1300px;margin:auto;padding:18px}.top{background:var(--blue);color:#fff;border-top:4px solid var(--red);border-radius:14px;padding:20px;display:flex;justify-content:space-between;gap:12px;align-items:center}.top h1{margin:0}.btn{display:inline-block;padding:10px 14px;border-radius:8px;text-decoration:none;font-weight:700;border:0}.white{background:#fff;color:var(--navy)}.navy{background:#1f5b98;color:#fff}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0}.metric,.card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:16px}.metric .label{font-size:12px;color:#68758a;text-transform:uppercase}.metric .value{font-size:25px;font-weight:800;color:var(--navy);margin-top:5px}.filters{display:flex;gap:10px;align-items:end;margin:14px 0;background:#fff;border:1px solid var(--line);border-radius:12px;padding:14px}.filters select{padding:10px;border:1px solid #cbd2df;border-radius:8px;min-width:220px}.grid2{display:grid;grid-template-columns:1fr 2fr;gap:14px}table{width:100%;border-collapse:collapse}th{background:#0f3769;color:#fff;padding:10px;text-align:left}td{padding:10px;border-bottom:1px solid #e7ebf1}.won{color:#18723a;font-weight:700}.lost{color:#a12525;font-weight:700}.money{text-align:right}.bar{height:10px;background:#e8edf4;border-radius:99px;overflow:hidden}.bar span{display:block;height:100%;background:#b73535}.muted{font-size:12px;color:#68758a}@media(max-width:850px){.cards{grid-template-columns:1fr 1fr}.grid2{grid-template-columns:1fr}.top{display:block}.top div:last-child{margin-top:10px}.filters{display:block}.filters select,.filters .btn{width:100%;margin-top:8px}.tablewrap{overflow-x:auto}}@media(max-width:520px){.cards{grid-template-columns:1fr}}
</style></head><body><main class="page"><div class="top"><div><h1>Closed Opportunities</h1><div>Won/Lost results and conversion performance.</div></div><div><a class="btn white" href="<?=htmlspecialchars(workflow_url(),ENT_QUOTES,'UTF-8')?>">← Sales Workflow</a> <a class="btn white" href="opportunities.php">Pipeline</a> <a class="btn white" href="opportunity-report.php">Reports</a> <a class="btn white" href="opportunity-funnel.php">Funnel</a></div></div>
<div class="cards"><div class="metric"><div class="label">Won</div><div class="value"><?=number_format((int)$summary['won_count'])?></div></div><div class="metric"><div class="label">Lost</div><div class="value"><?=number_format((int)$summary['lost_count'])?></div></div><div class="metric"><div class="label">Win Rate</div><div class="value"><?=number_format($winRate,1)?>%</div></div><div class="metric"><div class="label">Won Annual Revenue</div><div class="value"><?=opp_money($summary['won_revenue'])?></div></div><div class="metric"><div class="label">Won GP</div><div class="value"><?=opp_money($summary['won_gp'])?></div></div></div>
<form class="filters"><div><label style="font-size:12px;font-weight:700;color:#68758a">Sales Rep</label><select name="rep"><option value="">All reps</option><?php foreach($reps as $r):?><option value="<?=opp_h($r)?>" <?=$rep===$r?'selected':''?>><?=opp_h($r)?></option><?php endforeach;?></select></div><button class="btn navy">Apply</button></form>
<div class="grid2"><div class="card"><h3 style="margin-top:0;color:var(--navy)">Loss Reasons</h3><?php if(!$lossReasons):?><div class="muted">No lost opportunities recorded.</div><?php endif;?><?php $max=max(array_map(fn($r)=>(int)$r['cnt'],$lossReasons) ?: [1]); foreach($lossReasons as $r):?><div style="margin:10px 0"><div style="display:flex;justify-content:space-between"><span><?=opp_h($r['reason'])?></span><strong><?=number_format((int)$r['cnt'])?></strong></div><div class="bar"><span style="width:<?=($r['cnt']/$max)*100?>%"></span></div></div><?php endforeach;?></div>
<div class="card tablewrap"><table><thead><tr><th>Opportunity</th><th>Customer</th><th>Rep</th><th>Outcome</th><th>Date</th><th>Revenue</th><th>GP</th><th>Reason / PO</th><th></th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9">No closed opportunities yet.</td></tr><?php endif;?><?php foreach($rows as $r):$won=$r['status']==='Won';?><tr><td><?=opp_h($r['opportunity_no'])?></td><td><strong><?=opp_h($r['company_name'])?></strong></td><td><?=opp_h($r['lowe_rep'])?></td><td class="<?=$won?'won':'lost'?>"><?=opp_h($r['status'])?></td><td><?=opp_h($won?($r['won_date']??''):($r['lost_date']??''))?></td><td class="money"><?=$won?opp_money($r['actual_annual_revenue']??0):'—'?></td><td class="money"><?=$won?opp_money($r['actual_annual_gp']??0):'—'?></td><td><?=opp_h($won?($r['po_number']??''):($r['lost_reason']??''))?></td><td><a class="btn navy" href="opportunity.php?id=<?=(int)$r['id']?>">Open</a></td></tr><?php endforeach;?></tbody></table></div></div>
</main></body></html>