<?php
declare(strict_types=1);require_once __DIR__.'/inventory-model.php';
$q=trim((string)($_GET['q']??''));$min=max(0,(int)($_GET['months']??6));$ageView=(string)($_GET['age']??'all');
$rows=[];$today=strtotime(date('Y-m-d'));
try{$invLots=ld_rows('Inventory');}catch(Throwable $e){die(ld_h($e->getMessage()));}
$lotAgg=[];
foreach($invLots as $r){$code=im_code($r['Product Number']??'');if($code==='')continue;$lbs=of_num($r['Total LBs']??0);$val=of_num($r['Total Cost']??0);if($lbs<=0.00001&&$val<=0.00001)continue;if(!isset($lotAgg[$code]))$lotAgg[$code]=['age_lbs'=>array_fill_keys(['1-30','31-60','61-90','91-180','181-365','365+'],0.0),'age_value'=>array_fill_keys(['1-30','31-60','61-90','91-180','181-365','365+'],0.0),'lots'=>0,'expired_lbs'=>0.0,'expiring_90_lbs'=>0.0,'oldest_days'=>0];$d=im_date($r['Receipt Date']??'');$days=$d?max(0,(int)floor(($today-strtotime($d))/86400)):0;if($days<=30)$b='1-30';elseif($days<=60)$b='31-60';elseif($days<=90)$b='61-90';elseif($days<=180)$b='91-180';elseif($days<=365)$b='181-365';else$b='365+';$lotAgg[$code]['age_lbs'][$b]+=$lbs;$lotAgg[$code]['age_value'][$b]+=$val;$lotAgg[$code]['lots']++;$lotAgg[$code]['oldest_days']=max($lotAgg[$code]['oldest_days'],$days);$ed=im_date($r['Expire Date']??'');if($ed){$dd=(int)floor((strtotime($ed)-$today)/86400);if($dd<0)$lotAgg[$code]['expired_lbs']+=$lbs;elseif($dd<=90)$lotAgg[$code]['expiring_90_lbs']+=$lbs;}}
foreach($data['rows'] as $r){$on=(float)$r['on_hand_lbs'];if($on<=0.00001)continue;$sales=max(0.0,(float)$r['sales_365_lbs']);$months=$sales>0?($on/($sales/12)):9999.0;if($months<$min)continue;if($q!==''&&!ld_contains($r['product_name'],$q)&&!ld_contains($r['product_code'],$q)&&!ld_contains($r['primary_supplier'],$q))continue;$a=$lotAgg[$r['product_code']]??['age_lbs'=>[],'age_value'=>[],'lots'=>0,'expired_lbs'=>0,'expiring_90_lbs'=>0,'oldest_days'=>0];if($ageView==='over180'&&(($a['age_lbs']['181-365']??0)+($a['age_lbs']['365+']??0))<=0)continue;if($ageView==='over365'&&($a['age_lbs']['365+']??0)<=0)continue;if($ageView==='expiry'&&$a['expired_lbs']<=0&&$a['expiring_90_lbs']<=0)continue;$r['months_supply']=$months;$r['aging']=$a;$rows[]=$r;}
usort($rows,fn($a,$b)=>$b['inventory_value']<=>$a['inventory_value']);$lbs=array_sum(array_column($rows,'on_hand_lbs'));$val=array_sum(array_column($rows,'inventory_value'));
ld_head('Excess & Slow-Moving Inventory','Lot-level aging, cash exposure, and inventory that may need Sales attention');?>
<div class="cards"><div class="card"><div class="n"><?=count($rows)?></div><div class="l">Products Shown</div></div><div class="card"><div class="n"><?=ld_n($lbs)?> lb</div><div class="l">On Hand Inventory</div></div><div class="card"><div class="n"><?=ld_money($val)?></div><div class="l">Actual Inventory Value</div></div><div class="card"><div class="n"><?=$min?>+</div><div class="l">Months Supply Filter</div></div></div>
<section class="panel"><form class="filters"><div class="field wide"><label>Product / Code / Supplier</label><input name="q" value="<?=ld_h($q)?>"></div><div class="field"><label>Minimum Months Supply</label><select name="months"><?php foreach([3,6,9,12,18,24] as $m):?><option value="<?=$m?>" <?=$min===$m?'selected':''?>><?=$m?>+ months</option><?php endforeach;?></select></div><div class="field"><label>Inventory Age</label><select name="age"><option value="all">All ages</option><option value="over180" <?=$ageView==='over180'?'selected':''?>>Has inventory over 180 days</option><option value="over365" <?=$ageView==='over365'?'selected':''?>>Has inventory over 365 days</option><option value="expiry" <?=$ageView==='expiry'?'selected':''?>>Expiry attention</option></select></div><button class="btn">Run</button><a class="btn alt" href="slow-inventory.php">Reset</a></form></section>
<div class="tablewrap"><table><thead><tr><th class="left">Product #</th><th class="left prod">Product</th><th>On Hand LB</th><th>Sales 365D LB</th><th>Months Supply</th><th>Inventory Value</th><th>1-30D Value</th><th>31-60D</th><th>61-90D</th><th>91-180D</th><th>181-365D</th><th>365+D</th><th>Oldest Lot Days</th><th>Expired LB</th><th>Expiring 90D LB</th><th class="left">Primary Supplier</th><th class="left">Top Customer</th></tr></thead><tbody><?php foreach($rows as $r):$a=$r['aging'];?><tr><td class="left"><?=ld_h($r['product_code'])?></td><td class="left prod"><?=ld_h($r['product_name'])?></td><td><?=ld_n($r['on_hand_lbs'])?></td><td><?=ld_n($r['sales_365_lbs'])?></td><td class="<?=$r['months_supply']>=12?'neg':'soon'?>"><?=$r['months_supply']>=999?'No recent sales':ld_n($r['months_supply'],1)?></td><td><?=ld_money($r['inventory_value'])?></td><td><?=ld_money($a['age_value']['1-30']??0)?></td><td><?=ld_money($a['age_value']['31-60']??0)?></td><td><?=ld_money($a['age_value']['61-90']??0)?></td><td><?=ld_money($a['age_value']['91-180']??0)?></td><td><?=ld_money($a['age_value']['181-365']??0)?></td><td class="<?=($a['age_value']['365+']??0)>0?'neg':''?>"><?=ld_money($a['age_value']['365+']??0)?></td><td><?=ld_n($a['oldest_days']??0)?></td><td class="<?=$a['expired_lbs']>0?'neg':''?>"><?=ld_n($a['expired_lbs'])?></td><td class="<?=$a['expiring_90_lbs']>0?'soon':''?>"><?=ld_n($a['expiring_90_lbs'])?></td><td class="left"><?=ld_h($r['primary_supplier'])?></td><td class="left"><?=ld_h($r['top_customer'])?></td></tr><?php endforeach;?></tbody></table></div><div class="foot">Inventory aging and value now come directly from each current Inventory lot using Receipt Date, Total LBs, and Total Cost. Months supply uses trailing 365-day net invoiced pounds. Expiration flags use the lot-level Expire Date.</div><?php ld_foot(); ?>
